(ns com.blockether.vis.dev.companion-themes
  "Generate the Vis Companion's STATIC theme assets from `theme.clj`.

   The gateway used to serve `/v1/theme`, so a phone's palette was a network
   read against whichever machine it happened to be paired with — six machines
   answered six catalogs for data that never moves. Themes ARE static: this
   task renders every built-in palette into one stylesheet plus a catalog
   module the application ships, and the app paints by setting `data-theme` on
   the document element.

     clojure -X:companion-themes

   Both outputs are committed, and `companion-themes-test` fails the suite when
   they drift from the Clojure themes they were generated from."
  (:require [clojure.java.io :as io]
            [clojure.string :as str]
            [com.blockether.vis.internal.theme :as theme]))

(def default-dir
  "Where the companion keeps its generated theme assets, from the repo root."
  "apps/vis-companion/src/lib")

(def stylesheet-file-name "themes.generated.css")

(def catalog-file-name "themes.generated.ts")

(def ^:private banner-lines
  ["GENERATED by `clojure -X:companion-themes` from"
   "src/com/blockether/vis/internal/theme.clj — do not edit by hand."])

(defn- banner
  "The do-not-edit header, as a CSS block comment or as TS line comments."
  [line-comment?]
  (if line-comment?
    (str (str/join "\n"
                   (map (fn [line]
                          (str "// " line))
                        banner-lines))
         "\n\n")
    (str "/* " (first banner-lines) "\n   " (second banner-lines) " */\n\n")))

(defn theme-ids
  "Built-in theme ids in generation order: the default first (it is also the
   pre-hydration `:root` block), then the rest alphabetically. Extension themes
   are deliberately absent — a palette installed on ONE machine cannot paint an
   application that pairs with six of them."
  []
  (into [theme/default-theme-id]
        (sort (remove #{theme/default-theme-id} (keys theme/built-in-themes)))))

(defn- declarations
  [theme-map]
  (str "  color-scheme: " (name (:mode theme-map :light))
       ";\n" (str/join (map (fn [[css-var value]]
                              (str "  " css-var ": " value ";\n"))
                            (theme/theme->web-css-vars theme-map)))))

(defn- selector
  [id]
  (if (= id theme/default-theme-id)
    (str ":root,\n[data-theme='" id "']")
    (str "[data-theme='" id "']")))

(defn stylesheet
  "Every built-in palette as one static stylesheet: a `[data-theme='<id>']`
   block per theme, the default one doubling as `:root` so the first frame is
   already painted before any stored preference has been read."
  []
  (str (banner false)
       (str/join "\n"
                 (map
                   (fn [id]
                     (str (selector id) " {\n" (declarations (get theme/built-in-themes id)) "}\n"))
                   (theme-ids)))))

(defn- entry
  [id]
  (let [theme-map (get theme/built-in-themes id)]
    (str "{ id: '"
         id
         "', label: '"
         (:display-name theme-map)
         "', mode: '"
         (name (:mode theme-map))
         "', chrome: '"
         (theme/rgb->css (get-in theme-map [:palette :terminal-bg]))
         "' }")))

(defn catalog-module
  "The TypeScript catalog beside the stylesheet: what each palette is CALLED and
   which chrome colour it wants, for the picker and the `theme-color` meta. The
   colours themselves stay in CSS."
  []
  (let [[default-id & rest-ids] (theme-ids)]
    (str
      (banner true)
      "export interface ThemeChoice {\n"
      "  readonly id: string;\n"
      "  readonly label: string;\n"
      "  readonly mode: 'light' | 'dark';\n"
      "  /** This palette's `--bg`, for the browser chrome's `theme-color` meta. */\n"
      "  readonly chrome: string;\n"
      "}\n\n"
      "/** Painted before any stored preference is read, and the fallback for an unknown id. */\n"
      "export const DEFAULT_THEME: ThemeChoice = "
      (entry default-id)
      ";\n\n"
      "export const THEMES: readonly ThemeChoice[] = [\n"
      "  DEFAULT_THEME,\n"
      (str/join (map (fn [id]
                       (str "  " (entry id) ",\n"))
                     rest-ids))
      "];\n")))

(defn write!
  "Write both generated assets under `:dir` (default `default-dir`)."
  [{:keys [dir] :or {dir default-dir}}]
  (let [css
        (io/file dir stylesheet-file-name)

        catalog
        (io/file dir catalog-file-name)]

    (io/make-parents css)
    (spit css (stylesheet))
    (spit catalog (catalog-module))
    (println "wrote" (str css))
    (println "wrote" (str catalog))))
