(ns com.blockether.vis.dev.companion-themes
  "Generate the Vis Companion's STATIC colour assets from `theme.clj`.

   The gateway used to serve `/v1/theme`, so a phone's palette was a network
   read against whichever machine it happened to be paired with — six machines
   answered six catalogs for data that never moves. Themes ARE static: this
   task renders every built-in palette into one stylesheet plus a catalog
   module the application ships, and the app paints by setting `data-theme` on
   the document element.

   Session-group colours ship the same way. A group stores a palette TOKEN on the
   gateway; the tokens come from the gateway contract and their hues from
   `theme/session-group-swatches`, so the app keeps no palette of its own.

     clojure -X:companion-themes

   Every output is committed, and `companion-themes-test` fails the suite when
   one drifts from the Clojure data it was generated from."
  (:require [clojure.java.io :as io]
            [clojure.string :as str]
            [com.blockether.vis.contract.gateway :as gateway-contract]
            [com.blockether.vis.internal.channel.theme :as theme]))

(def default-dir
  "Where the companion keeps its generated theme assets, from the repo root."
  "apps/vis-companion/src/lib")

(def stylesheet-file-name "themes.generated.css")

(def catalog-file-name "themes.generated.ts")

(def group-colors-file-name "group-colors.generated.ts")

(def ^:private banner-lines
  ["GENERATED by `clojure -X:companion-themes` from"
   "src/com/blockether/vis/internal/channel/theme.clj — do not edit by hand."])

(defn- banner
  "The do-not-edit header, as a CSS block comment or as TS line comments."
  [line-comment?]
  (if line-comment?
    (str (str/join "\n"
                   (map (fn [line]
                          (str "// " line))
                        banner-lines))
         "\n\n")
    (str "/* " (first banner-lines) "\n   " (second banner-lines) " */\n\n")))

(defn theme-ids
  "Built-in theme ids in generation order: the default first (it is also the
   pre-hydration `:root` block), then the rest alphabetically. Extension themes
   are deliberately absent — a palette installed on ONE machine cannot paint an
   application that pairs with six of them."
  []
  (into [theme/default-theme-id]
        (sort (remove #{theme/default-theme-id} (keys theme/built-in-themes)))))

(defn- declarations
  [theme-map]
  (str "  color-scheme: " (name (:mode theme-map :light))
       ";\n" (str/join (map (fn [[css-var value]]
                              (str "  " css-var ": " value ";\n"))
                            (theme/theme->web-css-vars theme-map)))))

(defn- selector
  [id]
  (if (= id theme/default-theme-id)
    (str ":root,\n[data-theme='" id "']")
    (str "[data-theme='" id "']")))

(defn- group-hue
  "The CSS hue `theme.clj` gives a session-group token. A token without one fails
   generation instead of shipping a swatch that paints nothing."
  [token]
  (if-let [rgb (get theme/session-group-swatches token)]
    (theme/rgb->css rgb)
    (throw (ex-info "Session-group token has no hue in theme.clj" {:token token}))))

(defn- group-hues
  "One Tailwind `@theme` colour per session-group token, so `bg-group-<token>`
   fills a swatch, in the contract's order."
  []
  (str "/* Session-group hues, one per token of the gateway's closed palette. They sit\n"
       "   outside the themes above: a group keeps its colour when the theme changes. */\n"
       "@theme {\n"
       (str/join (map (fn [token]
                        (str "  --color-group-" token ": " (group-hue token) ";\n"))
                      gateway-contract/session-group-colors))
       "}\n"))

(defn stylesheet
  "Every built-in palette as one static stylesheet: a `[data-theme='<id>']`
   block per theme, the default one doubling as `:root` so the first frame is
   already painted before any stored preference has been read. The
   session-group hues every theme shares come last."
  []
  (str (banner false)
       (str/join "\n"
                 (map
                   (fn [id]
                     (str (selector id) " {\n" (declarations (get theme/built-in-themes id)) "}\n"))
                   (theme-ids)))
       "\n"
       (group-hues)))

(defn- entry
  [id]
  (let [theme-map (get theme/built-in-themes id)]
    (str "{ id: '"
         id
         "', label: '"
         (:display-name theme-map)
         "', mode: '"
         (name (:mode theme-map))
         "', chrome: '"
         (theme/rgb->css (get-in theme-map [:palette :terminal-bg]))
         "' }")))

(defn catalog-module
  "The TypeScript catalog beside the stylesheet: what each palette is CALLED and
   which chrome colour it wants, for the picker and the `theme-color` meta. The
   colours themselves stay in CSS."
  []
  (let [[default-id & rest-ids] (theme-ids)]
    (str
      (banner true)
      "export interface ThemeChoice {\n"
      "  readonly id: string;\n"
      "  readonly label: string;\n"
      "  readonly mode: 'light' | 'dark';\n"
      "  /** This palette's `--bg`, for the browser chrome's `theme-color` meta. */\n"
      "  readonly chrome: string;\n"
      "}\n\n"
      "/** Painted before any stored preference is read, and the fallback for an unknown id. */\n"
      "export const DEFAULT_THEME: ThemeChoice = "
      (entry default-id)
      ";\n\n"
      "export const THEMES: readonly ThemeChoice[] = [\n"
      "  DEFAULT_THEME,\n"
      (str/join (map (fn [id]
                       (str "  " (entry id) ",\n"))
                     rest-ids))
      "];\n")))

(defn group-colors-module
  "The session-group palette as TypeScript: the gateway contract's tokens in the
   order a picker offers them, its default, and the class that fills each token.
   Class names are written out whole because Tailwind scans source text; the hues
   stay in the stylesheet."
  []
  (let [tokens gateway-contract/session-group-colors]
    (str
      (banner true)
      "/** Every token a group may carry, in the order a picker offers them. */\n"
      "export const GROUP_COLORS = [\n"
      (str/join (map (fn [token]
                       (str "  '" token "',\n"))
                     tokens))
      "] as const;\n\n"
      "export type SessionGroupColor = (typeof GROUP_COLORS)[number];\n\n"
      "/** What a group with nothing said about its colour wears — the gateway's default too. */\n"
      "export const DEFAULT_GROUP_COLOR: SessionGroupColor = '"
      gateway-contract/default-session-group-color
      "';\n\n"
      "/** The class that fills each token's swatch; its hue is `--color-group-<token>`. */\n"
      "export const GROUP_SWATCHES: Readonly<Record<SessionGroupColor, string>> = {\n"
      (str/join (map (fn [token]
                       (str "  " token ": 'bg-group-" token "',\n"))
                     tokens))
      "};\n")))

(defn write!
  "Write every generated asset under `:dir` (default `default-dir`)."
  [{:keys [dir] :or {dir default-dir}}]
  (doseq [[file-name render] [[stylesheet-file-name stylesheet] [catalog-file-name catalog-module]
                              [group-colors-file-name group-colors-module]]]
    (let [file (io/file dir file-name)]
      (io/make-parents file)
      (spit file (render))
      (println "wrote" (str file)))))
