(ns com.blockether.vis.tui.html-backend-test
  (:require [clojure.data.json :as json]
            [clojure.java.io :as io]
            [com.blockether.vis.contract.activity :as activity-contract]
            [clojure.string :as str]
            [com.blockether.vis.tui.render :as render]
            [com.blockether.vis.tui.components :as components]
            [com.blockether.vis.tui.interactions :as interactions]
            [com.blockether.vis.tui.state :as state]
            [com.blockether.vis.tui.client :as client]
            [com.blockether.vis.tui.frame :as frame]
            [com.blockether.vis.tui.header :as header]
            [com.blockether.vis.tui.improve :as improve]
            [com.blockether.vis.tui.input :as input]
            [com.blockether.vis.tui.screen :as screen]
            [com.blockether.vis.tui.scroll :as scroll]
            [com.blockether.vis.tui.live-view :as live-view]
            [com.blockether.vis.tui.live-view-test :as live-fixture]
            [com.blockether.vis.tui.terminal-image :as timg]
            [com.blockether.vis.tui.theme :as theme]
            [com.blockether.vis.tui.theme-test :as theme-test]
            [com.blockether.vis.tui.shared-theme :as shared-theme]
            [lazytest.core :refer [defdescribe expect it]])
  (:import [com.googlecode.lanterna TerminalPosition TerminalSize]
           [com.googlecode.lanterna.gui2 Button GridLayout Panel TextGraphicsComponent]
           [com.googlecode.lanterna.input KeyStroke KeyType MouseAction MouseActionType]
           [com.googlecode.lanterna.screen TerminalScreen]
           [com.googlecode.lanterna.terminal.html HtmlMedia$Kind HtmlTerminal HtmlTerminalView]
           [com.googlecode.lanterna.terminal.virtual DefaultVirtualTerminal]))

(defn- cell-grid
  [^DefaultVirtualTerminal terminal cols rows]
  (mapv (fn [row]
          (mapv (fn [col]
                  (.getCharacter terminal (TerminalPosition. (int col) (int row))))
                (range cols)))
        (range rows)))

(defn activity-review-rows
  "Deterministic execution fixture for live HTML and native grid review."
  [state]
  (mapv (fn [i operation]
          (cond-> {:id (str "call-" i)
                   :sequence i
                   :operation operation
                   :presenter "generic"
                   :signal "generic"
                   :state "succeeded"
                   :summary (if (= operation "shell") "npm test" (str "src/file-" i ".clj"))
                   :resources
                   (if (= operation "shell") [] [{:type "file" :id (str "src/file-" i ".clj")}])
                   :evidence (if (= operation "patch")
                               [{:kind "diff"
                                 :text (str "src/file-" i ".clj")
                                 :additions 2
                                 :deletions 1
                                 :lines [{:kind "addition" :text "updated"}]}]
                               [])}
            (= i 6)
            (assoc :state state)

            (and (= i 6) (= state "failed"))
            (assoc :error-summary "Test suite failed")))
        (range 7)
        ["cat" "patch" "shell" "cat" "patch" "cat" "shell"]))

(defn activity-result-rows
  "Builtin result fixture generated by the engine and shared with Companion."
  []
  (-> (io/resource "vis-contract/fixtures/activity-results.json")
      slurp
      json/read-str
      activity-contract/from-wire
      :rows))

(defn activity-review-terminal
  "Configure review defaults to match the actual TUI theme, including empty cells."
  ^HtmlTerminal [cols rows]
  (doto (-> (HtmlTerminal/builder)
            (.initialSize (TerminalSize. cols rows))
            (.defaultForeground theme/text-fg)
            (.defaultBackground theme/terminal-bg)
            (.title "Activity review")
            (.build))
    (.setCursorVisible false)))

(defn paint-activity-review!
  "Paint the production joined execution surface; no copied browser layout."
  ([^TerminalScreen screen rows expansions] (paint-activity-review! screen rows expansions nil))
  ([^TerminalScreen screen rows expansions projection-extra]
   (paint-activity-review! screen rows expansions projection-extra nil))
  ([^TerminalScreen screen rows expansions projection-extra live-records]
   (.doResizeIfNecessary screen)
   (.clear screen)
   (let [cols
         (.getColumns (.getTerminalSize screen))

         height
         (.getRows (.getTerminalSize screen))

         projection
         (merge {:state "running"
                 :rows rows
                 :counts (merge {:running 0 :succeeded 0 :failed 0 :cancelled 0}
                                (frequencies (map (comp keyword :state) rows)))}
                projection-extra)

         rendered
         (render/format-answer-with-thinking-data*
           ""
           [{:thinking "Inspect files, apply the patch, then run tests."
             :iteration-id "activity-review-iteration"
             :attachments (:attachments live-records)
             :forms [{:code "inspect_files()\napply_patch()\nrun_checks()"
                      :stdout "Read 3 files.\nUpdated 2 files."
                      :duration-ms 1200
                      :activity projection}]}]
           (- cols 4)
           {:show-thinking true :show-iterations true}
           nil
           false
           {:session-id "activity-review"
            ;; The joined surface lives inside the step digest, so the review opens it.
            :detail-expansions (assoc expansions ["activity-review" "iteration:i1:digest"] true)
            :runs (:runs live-records)})]

     (doto (.newTextGraphics screen)
       (.setBackgroundColor theme/terminal-bg)
       (.setForegroundColor theme/text-fg)
       (.fill \space))
     (.beginFrame interactions/hit-map)
     (let [consumed (render/draw-chat-bubble! (.newTextGraphics screen)
                                              {:role :assistant
                                               :text ""
                                               :prewrapped-lines (:lines rendered)
                                               :line-meta (:line-meta rendered)}
                                              2
                                              1
                                              (- cols 4)
                                              {:viewport-h (- height 2)})]
       (.commitFrame interactions/hit-map)
       (.refresh screen)
       (assoc rendered :review-rows (min height (+ 2 consumed)))))))

(defn toggle-review-region
  "Use the same pure detail event that mouse and keyboard dispatch in the TUI."
  [expansions region]
  (let [handler (:fn (get (deref (deref #'state/event-registry)) :toggle-detail))]
    (:detail-expansions (handler {:detail-expansions expansions :scroll scroll/follow}
                                 [:toggle-detail (:session-id region) (:node-id region)
                                  (:collapsed? region)]))))

(defdescribe
  activity-group-disclosure-isolation-test
  (it
    "activity group disclosure isolation"
    (doseq [cols
            [40 80 120]

            repeated?
            [false true]]

      (with-open [terminal
                  (DefaultVirtualTerminal. (TerminalSize. cols 80))

                  screen
                  (doto (TerminalScreen. terminal) (.startScreen))]

        (let [rows
              (mapv (fn [i]
                      (cond-> {:id (str "read-" i)
                               :sequence i
                               :operation "cat"
                               :state "succeeded"
                               :presentation {:headline "Read"
                                              :summary (str "file-" i ".clj")
                                              :content [{:type "text" :text (str "BODY_" i)}]}}
                        repeated?
                        (assoc :argument-key "same-arguments")))
                    (range 2))

              expansions
              (atom {})

              paint!
              #(paint-activity-review! screen rows @expansions)

              region
              (fn [suffix]
                (first (filter #(and (= :toggle-details (:kind %))
                                     (str/ends-with? (str (:node-id %)) suffix))
                               (.current interactions/hit-map))))

              click!
              (fn [suffix]
                (let [hit
                      (region suffix)

                      {:keys [row col]}
                      (:bounds hit)]

                  (expect (some? hit))
                  (when hit
                    (expect (= hit (.lookup interactions/hit-map (int (+ col 2)) (int row)))))
                  (swap! expansions toggle-review-region hit)
                  (paint!)))

              bodies
              (fn []
                (set (re-seq #"BODY_\d" (:text (paint!)))))]

          (paint!)
          (click! ":#band")
          ;; A group click must not recursively open every invocation body.
          (click! "#group")
          (expect (empty? (bodies)))
          (when repeated?
            (expect (true? (:collapsed? (region "#arguments"))))
            (click! "#arguments")
            (expect (empty? (bodies))))
          (expect (true? (:collapsed? (region ":read-0"))))
          (expect (true? (:collapsed? (region ":read-1"))))
          (click! ":read-0")
          (expect (= #{"BODY_0"} (bodies)))
          (expect (true? (:collapsed? (region ":read-1"))))
          ;; Reopening a parent preserves the one child the reader chose.
          (click! "#group")
          (expect (empty? (bodies)))
          (click! "#group")
          (expect (= #{"BODY_0"} (bodies)))
          (reset! expansions {:vis.channel-tui/baseline :expand})
          (expect (= #{"BODY_0" "BODY_1"} (bodies))))))))

(defdescribe
  activity-lint-sequence-disclosure-test
  (it "activity lint sequence disclosure"
      ;; Issue #270: a lint run that found something and its clean rerun join one
      ;; `Lint ×2` block. Each run has to name its place in the sequence, and closing
      ;; Activity has to keep every disclosure the reader left open or closed inside it.
      (with-open [terminal
                  (DefaultVirtualTerminal. (TerminalSize. 100 80))

                  screen
                  (doto (TerminalScreen. terminal) (.startScreen))]

        (let [rows
              [{:id "lint-0"
                :sequence 0
                :operation "lint"
                :state "succeeded"
                :presentation {:headline "Linted"
                               :summary "1 error · 0 warnings · 0 info · 2 files checked"
                               :content [{:type "text" :text "BODY_0"}]}}
               {:id "lint-1"
                :sequence 1
                :operation "lint"
                :state "succeeded"
                :presentation {:headline "Linted"
                               :summary "No lint findings · 2 files checked"
                               :content []
                               :sections [{:headline "Lint details"
                                           :summary ""
                                           :content [{:type "text" :text "BODY_1"}]}]}}]

              expansions
              (atom {})

              paint!
              #(paint-activity-review! screen rows @expansions)

              region
              (fn [suffix]
                (first (filter #(and (= :toggle-details (:kind %))
                                     (str/ends-with? (str (:node-id %)) suffix))
                               (.current interactions/hit-map))))

              click!
              (fn [suffix]
                (swap! expansions toggle-review-region (region suffix))
                (paint!))

              bodies
              (fn []
                (set (re-seq #"BODY_\d" (:text (paint!)))))

              text
              (fn []
                (str/join "\n" (:lines (paint!))))]

          (paint!)
          (click! ":#band")
          ;; Every group opens shut; one press shows its runs.
          (click! "#group")
          ;; The group counts its runs; each run says which one it is and how it ended.
          (expect (re-find #"Linted ×2" (text)))
          (expect (re-find #"1: Linted" (text)))
          (expect (re-find #"2: Linted" (text)))
          (expect (empty? (bodies)))
          ;; Opening one run leaves the other run and the clean run's details closed.
          (click! ":0:lint-0")
          (expect (= #{"BODY_0"} (bodies)))
          (click! ":#band")
          (click! ":#band")
          (expect (= #{"BODY_0"} (bodies)))
          ;; A collapsed run exposes nothing nested, not even its section header.
          (expect (nil? (region ":0:lint-1:section:0")))
          ;; And a run the reader collapsed stays collapsed the next time Activity opens.
          (click! ":0:lint-0")
          (click! ":#band")
          (click! ":#band")
          (expect (empty? (bodies)))
          (expect (true? (:collapsed? (region ":0:lint-0"))))
          ;; Nested content folds away with the run that holds it, and opening the run
          ;; again restores exactly the disclosures the reader left inside it.
          (click! ":0:lint-1")
          (click! ":0:lint-1:section:0")
          (expect (= #{"BODY_1"} (bodies)))
          (click! ":0:lint-1")
          (expect (empty? (bodies)))
          (expect (nil? (region ":0:lint-1:section:0")))
          (click! ":0:lint-1")
          (expect (= #{"BODY_1"} (bodies)))))))

(defdescribe
  result-first-html-native-parity-test
  (it
    "result first html native parity"
    (doseq [cols [40 80 120]]
      (with-open [html (activity-review-terminal cols 80)
                  terminal (DefaultVirtualTerminal. (TerminalSize. cols 80))
                  hs (doto (TerminalScreen. html) (.startScreen))
                  ts (doto (TerminalScreen. terminal) (.startScreen))]

        (let [rows (activity-result-rows)
              _ (paint-activity-review! hs rows {:vis.channel-tui/baseline :collapse})
              band (first (filter #(str/ends-with? (str (:node-id %)) ":#band")
                                  (.current interactions/hit-map)))
              opened (toggle-review-region {:vis.channel-tui/baseline :collapse} band)]

          (expect (= 6 (count rows)))
          (let [painted (paint-activity-review! hs rows opened)]
            (expect (= 2 (count (re-seq #"presenter\.clj" (str/join "\n" (:lines painted)))))))
          (doseq [[row expected disclosure?] (map vector
                                                  rows
                                                  ["presenter.clj" "Hi" "grep 'greeting'"
                                                   "retained result" "disclosure" "disclosure"]
                                                  [false true false true true true])]
            (paint-activity-review! hs rows opened)
            (let [step (first (filter #(str/ends-with? (str (:node-id %)) (str ":" (:id row)))
                                      (.current interactions/hit-map)))
                  expanded (if step (toggle-review-region opened step) opened)
                  _ (paint-activity-review! hs rows expanded)
                  _ (paint-activity-review! ts rows expanded)
                  grid (cell-grid terminal cols 80)
                  text (str/join "\n"
                                 (map #(apply str
                                         (map (fn [cell]
                                                (.getCharacterString cell))
                                              %))
                                      grid))]

              (expect (= disclosure? (some? step)))
              (expect (= (cell-grid html cols 80) grid))
              (expect (str/includes? text expected))
              (expect (not (re-find #"Thread id|Is pass" text)))
              (expect (not (re-find #"12:abc|13:def|\[\"src/com" text))))))))))

(defn activity-table-rows
  "Repeated-table fixture shared with Companion; unequal labels and multiline Unicode."
  []
  (-> (io/resource "vis-contract/fixtures/activity-tables.json")
      slurp
      json/read-str
      activity-contract/from-wire
      :rows))

(defdescribe
  activity-tables-html-native-parity-test
  (it "activity tables html native parity"
      (doseq [cols [40 80 120]]
        (with-open [html (activity-review-terminal cols 80)
                    terminal (DefaultVirtualTerminal. (TerminalSize. cols 80))
                    hs (doto (TerminalScreen. html) (.startScreen))
                    ts (doto (TerminalScreen. terminal) (.startScreen))]

          (let [rows (activity-table-rows)
                expansions {:vis.channel-tui/expand-execution-details? true
                            :vis.channel-tui/expand-all-details? true}]

            (paint-activity-review! hs rows expansions)
            (paint-activity-review! ts rows expansions)
            (let [grid (cell-grid terminal cols 80)
                  headers (keep-indexed (fn [y row]
                                          (let [text
                                                (apply str
                                                  (map #(.getCharacterString
                                                          ^com.googlecode.lanterna.TextCharacter %)
                                                       row))]
                                            (when-let [x (str/index-of text "Result")]
                                              [x y])))
                                        grid)]

              (expect (= (cell-grid html cols 80) grid))
              (expect (= 3 (count headers)))
              (expect (apply = (map first headers)))
              (doseq [[x y] headers]
                (expect (.isBold ^com.googlecode.lanterna.TextCharacter (get-in grid [y x]))))))))))

(defdescribe
  execution-result-html-native-parity-test
  (it "execution result html native parity"
      (let [rows (-> (io/resource "vis-contract/fixtures/activity-execution.json")
                     slurp
                     json/read-str
                     activity-contract/from-wire
                     :rows)]
        (doseq [cols [40 80 120]]
          (with-open [html (activity-review-terminal cols 100)
                      terminal (DefaultVirtualTerminal. (TerminalSize. cols 100))
                      hs (doto (TerminalScreen. html) (.startScreen))
                      ts (doto (TerminalScreen. terminal) (.startScreen))]

            (paint-activity-review! hs rows {:vis.channel-tui/baseline :collapse})
            (let [band (first (filter #(str/ends-with? (str (:node-id %)) ":#band")
                                      (.current interactions/hit-map)))
                  band-opened (toggle-review-region {:vis.channel-tui/baseline :collapse} band)
                  _ (paint-activity-review! hs rows band-opened)
                  group (first (filter #(str/ends-with? (str (:node-id %)) "#group")
                                       (.current interactions/hit-map)))
                  opened (toggle-review-region band-opened group)]

              (doseq [row rows]
                (paint-activity-review! hs rows opened)
                (let [step (first (filter #(str/ends-with? (str (:node-id %)) (str ":" (:id row)))
                                          (.current interactions/hit-map)))
                      expanded (toggle-review-region opened step)]

                  (expect (some? step))
                  (paint-activity-review! hs rows expanded)
                  (paint-activity-review! ts rows expanded)
                  (expect (= (cell-grid html cols 100) (cell-grid terminal cols 100)))))))))))

(defdescribe
  nested-result-execution-disclosures-test
  (it
    "nested result execution disclosures"
    ;; Result stays inside Code; Activity remains independent through every fold state.
    (try
      (doseq [theme-id (map keyword (shared-theme/available-theme-ids))]
        (theme/apply-theme! theme-id)
        (doseq [cols [40 80 160]
                status ["running" "succeeded" "failed"]]

          (with-open [html (activity-review-terminal cols 50)
                      hs (doto (TerminalScreen. html) (.startScreen))
                      terminal (DefaultVirtualTerminal. (TerminalSize. cols 50))
                      ts (doto (TerminalScreen. terminal) (.startScreen))]

            (let [rows (activity-review-rows status)
                  _ (paint-activity-review! hs rows {})
                  code-region (first (filter #(str/ends-with? (str (:node-id %)) ":code")
                                             (.current interactions/hit-map)))
                  _ (paint-activity-review! hs rows (toggle-review-region {} code-region))
                  regions (into [code-region]
                                (map (fn [suffix]
                                       (first (filter #(str/ends-with? (str (:node-id %)) suffix)
                                                      (.current interactions/hit-map))))
                                     [":result" ":#band"]))]

              (expect (every? some? regions))
              (doseq [result-open? [false true]
                      code-open? [false true]
                      activity-open? [false true]]

                (let [open-states [code-open? result-open? activity-open?]
                      expansions (reduce (fn [folds [region open?]]
                                           (assoc folds
                                             [(:session-id region) (:node-id region)] open?))
                                         {:vis.channel-tui/baseline :collapse}
                                         (map vector regions open-states))
                      _ (paint-activity-review! hs rows expansions)
                      _ (paint-activity-review! ts rows expansions)
                      grid (cell-grid terminal cols 50)
                      lines (mapv (fn [row]
                                    (apply str
                                      (map #(.getCharacterString
                                              ^com.googlecode.lanterna.TextCharacter %)
                                           row)))
                                  grid)
                      row-of (fn [label]
                               (first (keep-indexed #(when (str/includes? %2 label) %1) lines)))
                      labels (if code-open? ["CODE" "RESULT" "ACTIVITY"] ["CODE" "ACTIVITY"])
                      positions (mapv row-of labels)
                      text (str/join "\n" lines)
                      code-bg theme/code-block-bg]

                  (expect (= (cell-grid html cols 50) grid))
                  (expect (every? some? positions))
                  (expect (apply < positions))
                  (expect (not-any? #(str/starts-with? % " │") lines))
                  (expect (= (and code-open? result-open?) (str/includes? text "Read 3 files.")))
                  (expect (= code-open? (some? (row-of "RESULT"))))
                  (expect (= code-open? (str/includes? text "inspect_files()")))
                  (expect (= activity-open? (str/includes? text "Read ×3")))
                  (when activity-open?
                    (let [header-row (row-of "ACTIVITY")]
                      (expect (str/blank? (nth lines (inc header-row))))
                      (expect (= (mapv #(+ header-row %) [2 3 4])
                                 (mapv row-of ["Read ×3" "Patch ×2" "Shell ×2"])))))
                  (let [y (row-of "ACTIVITY")
                        x (str/index-of (nth lines y) "ACTIVITY")]

                    (expect (= theme/code-block-fg
                               (.getForegroundColor ^com.googlecode.lanterna.TextCharacter
                                                    (get-in grid [y x])))))
                  (doseq [y (range (row-of "CODE") (inc (long (row-of "ACTIVITY"))))]
                    (expect (= code-bg
                               (.getBackgroundColor ^com.googlecode.lanterna.TextCharacter
                                                    (get-in grid [y 2])))))
                  (doseq [[label row open?]
                          (map vector
                               labels
                               positions
                               (if code-open? open-states [code-open? activity-open?]))]
                    (let [col (str/index-of (nth lines row) label)
                          hit (.lookup interactions/hit-map (TerminalPosition. (int col) (int row)))
                          background-at (fn [y]
                                          (.getBackgroundColor
                                            ^com.googlecode.lanterna.TextCharacter
                                            (get-in grid [y col])))]

                      ;; Expanding Code must retain a single filled band, including Result
                      ;; and the blank row above each disclosure.
                      (expect (str/blank? (nth lines (dec row))))
                      (expect (= code-bg (background-at (dec row))))
                      (expect (= code-bg (background-at row)))
                      (expect (= :toggle-details (:kind hit)))
                      (expect (= (not open?) (:collapsed? hit)))))))))))
      (finally (theme/apply-theme! (keyword shared-theme/default-theme-id))))))

(defdescribe
  execution-header-copy-and-right-inset-test
  (it "execution header copy and right inset"
      ;; Copy uses the header button style without moving its six-cell click target.
      (try
        (doseq [theme-id (map keyword (shared-theme/available-theme-ids))]
          (theme/apply-theme! theme-id)
          (doseq [cols [40 80 160]]
            (with-open [terminal (DefaultVirtualTerminal. (TerminalSize. cols 50))
                        ts (doto (TerminalScreen. terminal) (.startScreen))]

              (paint-activity-review! ts (activity-review-rows "succeeded") {})
              (components/button! (.newTextGraphics ts) 0 0 " COPY " :copy-code {:register? false})
              (.refresh ts)
              (let [grid (cell-grid terminal cols 50)
                    row-text
                    (fn [row]
                      (apply str
                        (map #(.getCharacterString ^com.googlecode.lanterna.TextCharacter %) row)))
                    code-row (first (filter #(str/includes? (row-text %) "CODE") grid))
                    activity-row (first (filter #(str/includes? (row-text %) "ACTIVITY") grid))]

                (expect (= (- cols 6) (count (str/trimr (row-text code-row)))))
                (expect (= (- cols 6) (count (str/trimr (row-text activity-row)))))
                (expect (str/ends-with? (str/trimr (row-text code-row)) " COPY"))
                (expect (= (subvec (first grid) 0 6) (subvec code-row (- cols 11) (- cols 5))))
                (expect (str/ends-with? (str/trimr (row-text activity-row)) " COPY"))
                (expect (= (subvec code-row (- cols 11) (- cols 5))
                           (subvec activity-row (- cols 11) (- cols 5))))
                (doseq [x (range (- cols 11) (- cols 5))]
                  (expect (= :copy-disclosure
                             (:kind (.lookup interactions/hit-map
                                             (TerminalPosition. (int x)
                                                                (.indexOf ^java.util.List grid
                                                                          activity-row)))))))
                (doseq [x (range (- cols 11) (- cols 5))]
                  (expect (= :copy-disclosure
                             (:kind (.lookup interactions/hit-map
                                             (TerminalPosition. (int x)
                                                                (.indexOf ^java.util.List grid
                                                                          code-row)))))))
                (doseq [cell (subvec code-row (- cols 11) (- cols 5))]
                  (expect (not (.isBold ^com.googlecode.lanterna.TextCharacter cell)))
                  (expect (= theme/button-fg
                             (.getForegroundColor ^com.googlecode.lanterna.TextCharacter cell)))
                  (expect (= theme/button-bg
                             (.getBackgroundColor ^com.googlecode.lanterna.TextCharacter cell)))
                  (expect (not= theme/code-block-bg
                                (.getBackgroundColor ^com.googlecode.lanterna.TextCharacter
                                                     cell))))))))
        (finally (theme/apply-theme! (keyword shared-theme/default-theme-id))))))

(defdescribe
  activity-row-tail-aligns-with-copy-button-test
  (it
    "activity row tail aligns with copy button"
    ;; #236: the live ellipsis and settled duration end at COPY's padded button edge.
    (doseq [cols
            [40 80 160]

            [row-state suffix]
            [[{:state "running"} "…"] [{:state "succeeded" :duration-ms 1420} "1.4s"]]]

      (with-open [terminal
                  (DefaultVirtualTerminal. (TerminalSize. cols 50))

                  ts
                  (doto (TerminalScreen. terminal) (.startScreen))]

        (paint-activity-review!
          ts
          [(merge
             {:id "run-tests" :sequence 0 :operation "suite" :presentation {:headline "Run tests"}}
             row-state)]
          {:vis.channel-tui/baseline :expand})
        (let [lines
              (mapv (fn [row]
                      (apply str
                        (map #(.getCharacterString ^com.googlecode.lanterna.TextCharacter %) row)))
                    (cell-grid terminal cols 50))

              activity-row
              (first (filter #(str/includes? % "Run tests") lines))

              copy-regions
              (filter #(= :copy-disclosure (:kind %)) (.current interactions/hit-map))]

          (expect (= 2 (count copy-regions)))
          (expect (str/ends-with? (str/trimr activity-row) suffix))
          (doseq [{:keys [bounds]} copy-regions]
            (expect (= (+ (:col bounds) (:width bounds)) (count (str/trimr activity-row)))
                    (str "Activity tail must align with COPY at " cols
                         " columns: " (pr-str activity-row)))))))))

(defdescribe
  execution-header-copy-hover-test
  (it
    "execution header copy hover"
    ;; #223: live and persisted COPY caps react independently and reset on leave.
    (try
      (doseq [theme-id
              (map keyword (shared-theme/available-theme-ids))

              cols
              [40 80 160]

              status
              ["running" "succeeded"]]

        (theme/apply-theme! theme-id)
        (binding [interactions/hit-map (interactions/create-hit-map)]
          (with-open [terminal (DefaultVirtualTerminal. (TerminalSize. cols 50))
                      ts (doto (TerminalScreen. terminal) (.startScreen))]

            (let [paint! #(paint-activity-review! ts (activity-review-rows status) {})
                  _ (paint!)
                  baseline (cell-grid terminal cols 50)
                  targets (filter #(= :copy-disclosure (:kind %)) (.current interactions/hit-map))]

              (expect (= 2 (count targets)))
              (doseq [{:keys [bounds]} targets
                      x (range (:col bounds) (+ (:col bounds) (:width bounds)))]

                (expect (.updateHovered interactions/hit-map
                                        (MouseAction. MouseActionType/MOVE
                                                      0
                                                      (TerminalPosition. (int x)
                                                                         (int (:row bounds))))))
                (paint!)
                (let [grid (cell-grid terminal cols 50)
                      y (:row bounds)
                      col (:col bounds)]

                  (expect (= (subvec (nth baseline y) 0 col) (subvec (nth grid y) 0 col)))
                  (doseq [cell (subvec (nth grid y) col (+ col 6))]
                    (expect (.isBold ^com.googlecode.lanterna.TextCharacter cell))
                    (expect (= theme/header-active-tab-accent
                               (.getBackgroundColor ^com.googlecode.lanterna.TextCharacter cell))))
                  (expect (= (vec (concat (subvec baseline 0 y) (subvec baseline (inc y))))
                             (vec (concat (subvec grid 0 y) (subvec grid (inc y)))))))
                (.updateHovered interactions/hit-map
                                (MouseAction. MouseActionType/MOVE 0 (TerminalPosition. 0 0)))
                (paint!)
                (expect (= baseline (cell-grid terminal cols 50))))))))
      (finally (theme/apply-theme! (keyword shared-theme/default-theme-id))))))

(defdescribe
  joined-activity-html-native-parity-test
  (it
    "joined activity html native parity"
    (doseq [cols
            [40 80 120]

            status
            ["running" "succeeded" "failed"]]

      (let [size
            (TerminalSize. cols 50)

            rows
            (activity-review-rows status)]

        (with-open [html
                    (activity-review-terminal cols 50)

                    terminal
                    (DefaultVirtualTerminal. size)

                    hs
                    (doto (TerminalScreen. html) (.startScreen))

                    ts
                    (doto (TerminalScreen. terminal) (.startScreen))]

          (paint-activity-review! hs rows {:vis.channel-tui/baseline :collapse})
          (let [band
                (first (filter #(str/ends-with? (str (:node-id %)) ":#band")
                               (.current interactions/hit-map)))

                opened-band
                (toggle-review-region {:vis.channel-tui/baseline :collapse} band)

                _
                (paint-activity-review! hs rows opened-band)

                read-group
                (first (filter #(str/ends-with? (str (:node-id %)) "call-0#group")
                               (.current interactions/hit-map)))

                expanded
                (toggle-review-region opened-band read-group)

                collapsed
                {:vis.channel-tui/baseline :collapse}]

            (expect (some? band))
            (expect (some? read-group))
            (doseq [expansions [{} expanded collapsed]]
              (paint-activity-review! hs rows expansions)
              (paint-activity-review! ts rows expansions)
              (expect (= (cell-grid html cols 50) (cell-grid terminal cols 50)))
              (expect (str/includes? (.renderHtml html) "ACTIVITY")))
            (paint-activity-review! hs rows expanded)
            (let [rendered (paint-activity-review! ts rows expanded)]
              (expect (some #(str/includes? % "src/file-0.clj") (:lines rendered)))
              ;; The failed run sits in its own closed group: the tone counts it, no body shows.
              (when (= status "failed")
                (expect (not-any? #(str/includes? % "Test suite failed") (:lines rendered)))))
            ;; A streamed replacement keeps the group's manual expansion.
            (let [replacement
                  (paint-activity-review! ts (activity-review-rows "succeeded") expanded)]
              (expect (some #(str/includes? % "src/file-0.clj") (:lines replacement))))))))))

(defdescribe
  joined-execution-text-left-edge-test
  (it "joined execution text left edge"
      ;; Code, Result and Activity share the transcript edge without a rail.
      (doseq [cols [40 80 120]]
        (with-open [terminal (DefaultVirtualTerminal. (TerminalSize. cols 50))
                    screen (doto (TerminalScreen. terminal) (.startScreen))]

          (let [rows (activity-review-rows "failed")
                _ (paint-activity-review! screen rows {})
                hits (.current interactions/hit-map)
                code (first (filter #(str/ends-with? (str (:node-id %)) ":code") hits))
                band (first (filter #(str/ends-with? (str (:node-id %)) ":#band") hits))
                opened-band (toggle-review-region {} band)
                expanded (toggle-review-region opened-band code)]

            (expect (some? code))
            (expect (some? band))
            ;; Activity starts collapsed; open it before comparing its child rows.
            (doseq [[code-expanded? expansions] [[false opened-band] [true expanded]]]
              (paint-activity-review! screen rows expansions)
              (let [lines (mapv (fn [row]
                                  (apply str
                                    (map #(.getCharacterString
                                            ^com.googlecode.lanterna.TextCharacter %)
                                         row)))
                                (cell-grid terminal cols 50))
                    column (fn [text]
                             (some #(when (str/includes? % text) (str/index-of % text)) lines))]

                (expect (= (+ 2 (column "Vis")) (column "Inspect files")))
                (doseq [label (if code-expanded? ["CODE" "RESULT" "ACTIVITY"] ["CODE" "ACTIVITY"])]
                  (expect (= (+ 2 (column "Vis")) (column label))))
                (expect (= (column "ACTIVITY") (column "Read ×3")))
                (expect (some #(re-find #"Shell ×2 ▸ · 1 failed" %) lines))
                (expect (not-any? #(str/includes? % "│") lines))
                (if code-expanded?
                  (do (expect (= (column "CODE") (column "inspect_files()")))
                      (expect (some #(re-find #"RESULT  \+2 more ▸" %) lines)))
                  (do (expect (nil? (column "RESULT")))
                      (expect (some #(re-find #"CODE  \+3 more ▸" %) lines)))))))))))

(defdescribe
  joined-execution-background-and-disclosure-test
  (it
    "joined execution background and disclosure"
    ;; Removing the rail preserves filled execution bands and their disclosures.
    (doseq [cols
            [40 80 160]

            expanded?
            [false true]]

      (with-open [terminal
                  (DefaultVirtualTerminal. (TerminalSize. cols 50))

                  screen
                  (doto (TerminalScreen. terminal) (.startScreen))]

        (paint-activity-review! screen
                                (activity-review-rows "succeeded")
                                {:vis.channel-tui/baseline (if expanded? :expand :collapse)})
        (let [grid
              (cell-grid terminal cols 50)

              lines
              (mapv (fn [row]
                      (apply str
                        (map #(.getCharacterString ^com.googlecode.lanterna.TextCharacter %) row)))
                    grid)

              band-rows
              (keep-indexed (fn [row cells]
                              (when (= theme/code-block-bg
                                       (.getBackgroundColor ^com.googlecode.lanterna.TextCharacter
                                                            (nth cells 1)))
                                row))
                            grid)

              bottom
              (last band-rows)

              chevron
              (if expanded? "▾" "▸")]

          (expect (seq band-rows))
          (expect (= #{theme/code-block-bg}
                     (set (for [row
                                band-rows

                                col
                                (range 1 4)]

                            (.getBackgroundColor ^com.googlecode.lanterna.TextCharacter
                                                 (get-in grid [row col])))))
                  "Execution fills reach the left text edge")
          (doseq [label ["CODE" "ACTIVITY"]]
            (let [row (first (keep-indexed #(when (str/includes? %2 label) %1) lines))
                  line (nth lines row)
                  col (+ (str/index-of line label) (count label) 1)
                  hit (.lookup interactions/hit-map (TerminalPosition. (int col) (int row)))]

              (expect (re-find (re-pattern
                                 (str label
                                      (if (and (= label "CODE") (not expanded?)) "  \\+3 more" "")
                                      " "
                                      chevron))
                               line))
              (expect (= :toggle-details (:kind hit)))
              (expect (= (not expanded?) (:collapsed? hit)))))
          (expect (str/blank? (subs (nth lines bottom) 2))
                  "One empty execution row remains below the last content row")
          (expect (= #{theme/code-block-bg}
                     (set (map #(.getBackgroundColor ^com.googlecode.lanterna.TextCharacter %)
                               (subvec (nth grid bottom) 1 (- cols 3)))))))))))

(defdescribe
  live-execution-bottom-padding-test
  (it "live execution bottom padding"
      ;; Live margin trimming must not remove the filled Activity bottom edge.
      (doseq [status
              ["running" "succeeded" "failed"]

              expanded?
              [false true]]

        (let [payload
              (render/progress->lines-data
                {:iterations [{:forms [{:code "inspect_files()"
                                        :activity {:state status
                                                   :rows (activity-review-rows status)}}]}]}
                80
                {:show-iterations true}
                {:session-id "live-padding"
                 :now-ms 1000
                 :detail-expansions {:vis.channel-tui/expand-all-details? expanded?
                                     ["live-padding" "iteration:i1:digest"] true}})

              lines
              (:lines payload)

              last-band-row
              (last (keep-indexed #(when (str/starts-with? %2 @#'render/activity-marker) %1)
                                  lines))]

          (expect (= @#'render/activity-marker (nth lines last-band-row)))
          (expect (= "" (nth lines (inc last-band-row))))
          (expect (str/includes? (nth lines (+ last-band-row 2)) "Esc to cancel"))))))

(defdescribe
  screen-accepts-a-transport-neutral-html-terminal-test
  (it "screen accepts a transport neutral html terminal"
      (with-open [terminal (-> (HtmlTerminal/builder)
                               (.build))]
        (expect (identical? terminal (#'screen/create-terminal! {:html-terminal terminal})))
        (expect (.contains (.renderLiveHtml terminal "/tui") "data-endpoint-prefix=\"/tui\""))
        (let [method-names (set (map #(.getName ^java.lang.reflect.Method %)
                                     (.getMethods HtmlTerminal)))]
          (expect (not-any? method-names ["getUrl" "getUri" "getPort" "hasEmbeddedServer"]))))))

(defdescribe
  html-media-uses-the-resolved-image-cell-box-test
  (it
    "html media uses the resolved image cell box"
    (let [terminal
          (-> (HtmlTerminal/builder)
              (.initialSize (TerminalSize. 40 12))
              (.build))

          active
          (deref #'screen/active-html-terminal)

          region
          {:row 3
           :col 4
           :img {:id "turn-1-image-1" :path "/tmp/preview.png" :mime "image/png" :cols 8 :rows 5}}]

      (try (reset! active terminal)
           (timg/set-backend! :html)
           (with-redefs [timg/video-source?
                         (constantly false)

                         timg/html-png-data
                         (fn [_ _]
                           (byte-array [1 2 3]))]

             (#'screen/paint-terminal-images! [region])
             (let [media (first (.getMedia terminal))]
               (expect (= 1 (count (.getMedia terminal))))
               (expect (= "turn-1-image-1" (.getId media)))
               (expect (= HtmlMedia$Kind/IMAGE (.getKind media)))
               (expect (= (TerminalPosition. 4 3) (.getPosition media)))
               (expect (= (TerminalSize. 8 5) (.getSize media))))
             (#'screen/drop-terminal-images!)
             (expect (empty? (.getMedia terminal))))
           (finally (reset! active nil) (timg/set-backend! :native) (.close terminal))))))

(defdescribe html-backend-reserves-inline-image-layout-test
             (it "html backend reserves inline image layout"
                 (try (timg/set-backend! :html)
                      (expect (= :html (timg/images-protocol)))
                      (expect (true? (timg/graphical-terminal?)))
                      (finally (timg/set-backend! :native)))))

(defdescribe header-actions-use-lanterna-grid-and-render-alone-test
             (it "header actions use lanterna grid and render alone"
                 (let [panel
                       (header/header-actions-component)

                       preferred
                       (.getPreferredSize ^Panel panel)

                       html
                       (HtmlTerminalView/render panel preferred "Vis header actions")]

                   (expect (instance? GridLayout (.getLayoutManager ^Panel panel)))
                   (expect (every? #(instance? Button %) (.getChildrenList ^Panel panel)))
                   (expect (= 1 (.getRows preferred)))
                   (expect (.contains html "Vis header actions"))
                   (expect (.contains html "help ("))
                   (expect (.contains html "data-live=\"false\"")))))

(defdescribe header-actions-run-as-an-interactive-html-component-test
             (it "header actions run as an interactive html component"
                 (let [triggered
                       (promise)

                       panel
                       (header/header-actions-component #(deliver triggered %))

                       view
                       (HtmlTerminalView/start panel
                                               (.getPreferredSize ^Panel panel)
                                               "Interactive Vis header")]

                   (try (.addInput (.getTerminal view) (KeyStroke. KeyType/Enter))
                        (expect (= :header-help (deref triggered 3000 ::timeout)))
                        (expect (.contains (.renderHtml view) "help ("))
                        (finally (.close view))))))

(defdescribe
  all-terminal-surfaces-enter-through-the-grid-test
  (it "all terminal surfaces enter through the grid"
      (let [source-root
            (-> (io/resource "com/blockether/vis/tui/frame.clj")
                .toURI
                io/file
                .getParentFile)

            calls-by-file
            (into (sorted-map)
                  (keep (fn [file]
                          (when (and (.isFile file) (.endsWith (.getName file) ".clj"))
                            (let [calls (count (re-seq #"\.newTextGraphics" (slurp file)))]
                              (when (pos? calls) [(.getName file) calls])))))
                  (file-seq source-root))]

        ;; Dialogs, render and screen create only child clips from grid-owned graphics.
        ;; Every terminal-screen root and section clip is centralized in frame.
        (expect (= {"dialogs.clj" 1 "frame.clj" 5 "render.clj" 1 "screen.clj" 1} calls-by-file)))))

(defdescribe full-screen-surfaces-use-one-lanterna-grid-test
             (it "full screen surfaces use one lanterna grid"
                 (let [{:keys [panel sections]}
                       (frame/layout 80 30 {:header 3 :attachments 2 :composer 3 :footer 2})

                       bounds
                       (update-vals sections frame/bounds)]

                   (expect (instance? GridLayout (.getLayoutManager ^Panel panel)))
                   (expect (= [:header :header-gap :transcript :echo :attachments :composer :footer]
                              (vec (keys sections))))
                   (expect (every? #(instance? TextGraphicsComponent %) (vals sections)))
                   (expect (= {:col 0 :row 0 :cols 80 :rows 3} (:header bounds)))
                   ;; Keep a fixed blank row below the header while the transcript scrolls.
                   (expect (= {:col 0 :row 3 :cols 80 :rows 1} (:header-gap bounds)))
                   (expect (= {:col 0 :row 4 :cols 80 :rows 18} (:transcript bounds)))
                   (expect (= {:col 0 :row 22 :cols 80 :rows 1} (:echo bounds)))
                   (expect (= {:col 0 :row 23 :cols 80 :rows 2} (:attachments bounds)))
                   (expect (= {:col 0 :row 25 :cols 80 :rows 3} (:composer bounds)))
                   (expect (= {:col 0 :row 28 :cols 80 :rows 2} (:footer bounds))))))

(defdescribe
  grid-sections-fill-every-supported-column-count-test
  (it "grid sections fill every supported column count"
      (doseq [cols (range 20 401)]
        (let [sections (:sections
                         (frame/layout cols 40 {:header 3 :attachments 2 :composer 4 :footer 2}))
              bounds (mapv (comp frame/bounds sections) frame/section-order)]

          (expect (every? #(= {:col 0 :cols cols} (select-keys % [:col :cols])) bounds)
                  (str "every section fills " cols " columns"))
          (expect (= (mapv :row bounds) (vec (butlast (reductions + 0 (map :rows bounds)))))
                  (str "sections are contiguous at " cols " columns"))
          (expect (= 40 (reduce + (map :rows bounds)))
                  (str "sections fill every row at " cols " columns"))))))

(defdescribe
  laid-out-section-painters-stay-inside-their-grid-cell-test
  (it "laid out section painters stay inside their grid cell"
      (let [terminal
            (DefaultVirtualTerminal. (TerminalSize. 12 5))

            screen
            (doto (TerminalScreen. terminal) (.startScreen))

            root
            (frame/layout 12
                          5
                          {:header 1 :attachments 0 :composer 0 :footer 0}
                          {:transcript (fn [graphics _]
                                         (.putString graphics 0 1 "above")
                                         (.putString graphics 0 2 "inside")
                                         (.putString graphics 0 4 "below"))})]

        (try (frame/paint! (.newTextGraphics screen) root :transcript)
             (.refresh screen)
             (expect (= \space (.getCharacter (.getCharacter terminal (TerminalPosition. 0 1)))))
             (expect (= \i (.getCharacter (.getCharacter terminal (TerminalPosition. 0 2)))))
             (expect (= \space (.getCharacter (.getCharacter terminal (TerminalPosition. 0 4)))))
             (finally (.stopScreen screen))))))

(defdescribe
  complete-frame-cells-match-html-and-terminal-at-every-width-test
  (it
    "complete frame cells match html and terminal at every width"
    (let [rows
          32

          initial-size
          (TerminalSize. 20 rows)

          terminal
          (DefaultVirtualTerminal. initial-size)

          html
          (-> (HtmlTerminal/builder)
              (.initialSize initial-size)
              (.columnRange 20 400)
              (.rowRange rows rows)
              (.browserResize false)
              (.build))

          terminal-screen
          (doto (TerminalScreen. terminal) (.startScreen))

          html-screen
          (doto (TerminalScreen. html) (.startScreen))

          db
          {:config nil
           :session nil
           :title "Grid parity"
           :messages [{:id "user" :role :user :text "Zażółć gęślą — grid 界"}
                      {:id "assistant"
                       :role :assistant
                       :text "The same cells reach both backends."
                       :traces [{:forms [{:code "first_call()\nfirst_detail()" :success? true}
                                         {:code "second_call()" :success? true}]}]}]
           :scroll scroll/follow
           :input (input/paste-text (input/empty-input) "interactive draft")
           :settings {}
           :pending-sends []
           :detail-expansions {}
           :live-views []
           :loading? false
           :cancelling? false
           :progress nil
           :channel-status {}
           :tabs []
           :tab-locals {}
           :slash-command-index 0
           :render-version 0}]

      (try (doseq [cols (range 20 401)]
             (let [size (TerminalSize. cols rows)]
               (.setTerminalSize terminal size)
               (.setTerminalSize html size)
               (.doResizeIfNecessary terminal-screen)
               (.doResizeIfNecessary html-screen)
               ;; Compare one metadata snapshot, not two sides of an async footer refresh.
               (with-redefs [timg/images-protocol (constantly nil)
                             client/get-router (constantly nil)]

                 (#'screen/render-frame! terminal-screen cols rows db 1000)
                 (#'screen/render-frame! html-screen cols rows db 1000))
               (expect (= (cell-grid terminal cols rows) (cell-grid html cols rows))
                       (str "HTML and terminal cells differ at " cols " columns"))))
           (finally (.stopScreen terminal-screen)
                    (.stopScreen html-screen)
                    (.close html)
                    (.close terminal))))))

(defdescribe any-grid-view-renders-as-standalone-html-test
             (it "any grid view renders as standalone html"
                 (let [view
                       (frame/view 18
                                   2
                                   (fn [graphics _]
                                     (.putString graphics 0 0 "Standalone view")))

                       html
                       (HtmlTerminalView/render view (TerminalSize. 18 2) "Standalone Vis view")]

                   (expect (instance? GridLayout (.getLayoutManager ^Panel view)))
                   (expect (= 1 (count (.getChildrenList ^Panel view))))
                   (expect (.contains html ">Standalone</span>"))
                   (expect (.contains html ">view</span>"))
                   (expect (.contains html "Standalone Vis view")))))

(defdescribe
  grid-surface-owns-size-and-clipping-test
  (it "grid surface owns size and clipping"
      (let [terminal
            (DefaultVirtualTerminal. (TerminalSize. 12 5))

            screen
            (doto (TerminalScreen. terminal) (.startScreen))]

        (try (let [base (.newTextGraphics screen)]
               (.putString base 0 0 "K")
               (let [graphics (frame/surface-graphics screen 8 3)]
                 (expect (= (TerminalSize. 8 3) (.getSize graphics)))
                 (.putString graphics 7 2 "XY")
                 (.refresh screen)
                 (expect (= \K (.getCharacter (.getCharacter terminal (TerminalPosition. 0 0)))))
                 (expect (= \X (.getCharacter (.getCharacter terminal (TerminalPosition. 7 2)))))
                 (expect (= \space
                            (.getCharacter (.getCharacter terminal (TerminalPosition. 8 2)))))))
             (finally (.stopScreen screen))))))

(defn- caption-count
  "How many times one caption stands on a single painted row."
  [line phrase]
  (loop [from
         0

         n
         0]

    (if-let [at (str/index-of (str line) (str phrase) from)]
      (recur (+ (long at) (count (str phrase))) (inc n))
      n)))

(defdescribe
  activity-history-window-states-html-test
  (it "activity history window states html"
      ;; A paged Activity record stays readable in every fetch state: the search
      ;; offer, a search in flight, a changed record and a failed window all say
      ;; what happened and what one press does next.
      (let [rows
            (activity-review-rows "succeeded")

            history
            {:id "history-1" :revision 3 :total 90 :after 0 :next-after 7}

            states
            [[{} ["search every operation" "7 of 90 operations"]]
             [{"history-1" {:status :loading :after 0 :query "patch"}}
              ["searching every operation" "matching"]]
             [{"history-1" {:status :stale :after 0}} ["Activity changed" "show it again"]]
             [{"history-1" {:status :failed :after 7}} ["could not load"]]
             [{"history-1" {:query "patch"}}
              ["clear search" "showing 7 operations matching" "show more matching operations"]]]]

        (doseq [cols
                [80 120]

                [fetch expected]
                states]

          (with-open [html
                      (activity-review-terminal cols 60)

                      terminal
                      (DefaultVirtualTerminal. (TerminalSize. cols 60))

                      hs
                      (doto (TerminalScreen. html) (.startScreen))

                      ts
                      (doto (TerminalScreen. terminal) (.startScreen))]

            (let [extra
                  {:history history :vis.channel-tui/fetch fetch}

                  _
                  (paint-activity-review! hs rows {:vis.channel-tui/baseline :collapse} extra)

                  band
                  (first (filter #(str/ends-with? (str (:node-id %)) ":#band")
                                 (.current interactions/hit-map)))

                  opened
                  (toggle-review-region {:vis.channel-tui/baseline :collapse} band)]

              (expect (some? band))
              (paint-activity-review! hs rows opened extra)
              (paint-activity-review! ts rows opened extra)
              (let [text (str/join "\n"
                                   (map (fn [row]
                                          (apply str
                                            (map #(.getCharacterString
                                                    ^com.googlecode.lanterna.TextCharacter %)
                                                 row)))
                                        (cell-grid terminal cols 60)))]
                (doseq [phrase expected]
                  (expect (str/includes? text phrase)
                          (str "missing " (pr-str phrase) " at " cols " columns"))
                  ;; A rule paints its caption in the gap it cuts and the overlay only
                  ;; recolors that copy: the same words twice on one row is the bug.
                  (expect (every? #(<= (long (caption-count % phrase)) 1) (str/split-lines text))
                          (str "duplicated " (pr-str phrase) " on one row at " cols " columns")))
                (expect (= (cell-grid html cols 60) (cell-grid terminal cols 60)))
                (expect (str/includes? (.renderHtml html) "ACTIVITY")))))))))

(def ^:private improve-payload
  {"records" [{"id" 1 "title" "Slow startup" "status" "open" "project_id" "p1"}
              {"id" 2 "title" "Cold cache" "status" "open" "project_id" "p1" "parent_id" 1}
              {"id" 3 "title" "Stale index" "status" "closed" "project_id" "p1" "parent_id" 2}]
   "projects" [{"id" "p1" "name" "Editor"}]})

(defn- paint-improve-modal!
  "Paint one pure Improve component through a real screen, the way the dialog
   loop does it: measure, reconcile, then draw on the screen's own graphics. A
   component that answers a cursor position — the analysis editor — has it SET on
   the screen and handed back, so the caret is part of what the two backends have
   to agree on."
  ^TerminalPosition [^TerminalScreen screen component cols rows]
  (.doResizeIfNecessary screen)
  (.clear screen)
  (let [g
        (.newTextGraphics screen)

        geom
        ((:measure component) (:init component) cols rows)

        state
        ((:reconcile component) (:init component) geom)]

    (.setForegroundColor g theme/text-fg)
    (.setBackgroundColor g theme/terminal-bg)
    (.fill g \space)
    (let [caret ((:paint component) g state geom)]
      (when (instance? TerminalPosition caret) (.setCursorPosition screen ^TerminalPosition caret))
      (.refresh screen)
      (when (instance? TerminalPosition caret) caret))))

(defdescribe
  improve-register-and-mode-chooser-html-native-parity-test
  (it "improve register and mode chooser html native parity"
      ;; The Improve register and its mode chooser are ONE pure paint: the HTML view
      ;; a reviewer opens has to carry the same cells and the same words the
      ;; terminal shows, at a wide and at a narrow width.
      (doseq [cols
              [96 60]

              [component phrase]
              [[(improve/browser-modal-component (improve/records improve-payload)
                                                 (improve/project-names improve-payload)
                                                 nil
                                                 {:mode :human}) "Editor · 2 open of 3"]
               [(improve/settings-modal-component
                  {:mode :automatic :provider "anthropic" :model "claude" :interval-minutes 30})
                "Reviews every 30 minutes"]
               [(improve/analysis-editor-component "Analysis" "Wolny start\n\nDruga linia")
                "Druga linia"]]]

        (with-open [html
                    (activity-review-terminal cols 24)

                    terminal
                    (DefaultVirtualTerminal. (TerminalSize. cols 24))

                    hs
                    (doto (TerminalScreen. html) (.startScreen))

                    ts
                    (doto (TerminalScreen. terminal) (.startScreen))]

          (let [caret
                (paint-improve-modal! hs component cols 24)

                native-caret
                (paint-improve-modal! ts component cols 24)

                text
                (str/join "\n"
                          (map (fn [row]
                                 (apply str
                                   (map #(.getCharacterString ^com.googlecode.lanterna.TextCharacter
                                                              %)
                                        row)))
                               (cell-grid terminal cols 24)))]

            (expect (str/includes? text phrase)
                    (str "missing " (pr-str phrase) " at " cols " columns"))
            (expect (= (cell-grid html cols 24) (cell-grid terminal cols 24)))
            (expect (= caret native-caret)
                    (str "the caret lands in a different cell at " cols " columns"))
            (when caret
              (expect (= caret (.getCursorPosition hs)))
              (expect (= caret (.getCursorPosition ts)))))))))

(defn activity-live-records
  "Owned live receipt fixture for the production Activity renderer (#222)."
  []
  {:runs [{:view-id "jenkins-build"
           :title "Jenkins build pool"
           :reason :interrupted
           :lines 421
           :elapsed-ms 617000
           :owner {:invocation-id "jenkins-watch"}}]
   :attachments [{"source" "tool"
                  "kind" "doc"
                  "filename" "Jenkins.live.ndjson"
                  "media_type" "application/vnd.vis.live+ndjson"
                  "view_id" "jenkins-build"
                  "owner" {"invocation_id" "jenkins-watch"}}]})

(defn activity-live-rows
  "One deterministic operation owns the recorded Jenkins view."
  []
  [{:id "jenkins-watch"
    :sequence 1
    :operation "watch"
    :state "failed"
    :presentation {:headline "Watch Jenkins build" :summary "Build interrupted"}
    :evidence []}])

;; #222, #235: sibling ACTIVITY and LIVE share alignment, hit targets and background.
(defdescribe
  activity-live-sibling-grid-test
  (it
    "activity live sibling grid"
    (doseq [cols
            [40 80]

            recorded?
            [false true]]

      (with-open [html
                  (activity-review-terminal cols 50)

                  terminal
                  (DefaultVirtualTerminal. (TerminalSize. cols 50))

                  hs
                  (doto (TerminalScreen. html) (.startScreen))

                  ts
                  (doto (TerminalScreen. terminal) (.startScreen))]

        (let [records
              (cond-> (activity-live-records)
                (not recorded?)
                (dissoc :attachments))

              rows
              (activity-live-rows)]

          (paint-activity-review! hs rows {} nil records)
          (paint-activity-review! ts rows {} nil records)
          (expect (= (cell-grid html cols 50) (cell-grid terminal cols 50)))
          (let [grid
                (cell-grid terminal cols 50)

                lines
                (mapv #(apply str
                         (map (fn [^com.googlecode.lanterna.TextCharacter cell]
                                (.getCharacterString cell))
                              %))
                      grid)

                header-y
                (first (keep-indexed #(when (str/includes? %2 "ACTIVITY") %1) lines))

                live-y
                (first (keep-indexed #(when (str/includes? %2 "LIVE") %1) lines))

                live-x
                (.indexOf ^String (nth lines live-y) "LIVE")

                hit
                (.lookup interactions/hit-map live-x live-y)]

            (expect (< header-y live-y))
            (expect (= live-x (.indexOf ^String (nth lines header-y) "ACTIVITY")))
            (expect (str/blank? (nth lines (dec live-y))))
            (let [kind
                  (if recorded? :artifact :live-reopen)

                  button
                  ;; The digest also opens this view; select the control on the LIVE receipt.
                  (first (filter #(and (= kind (:kind %)) (= live-y (get-in % [:bounds :row])))
                                 (.current interactions/hit-map)))

                  {:keys [row col width]}
                  (:bounds button)]

              (expect (not= kind (:kind hit)))
              (expect (= live-y row))
              (expect (= " Recorded " (subs (nth lines row) col (+ col width))))
              (expect (= button (.lookup interactions/hit-map col row))))
            (doseq [y (range header-y (inc live-y))]
              (expect (= theme/code-block-bg
                         (.getBackgroundColor ^com.googlecode.lanterna.TextCharacter
                                              (get-in grid [y live-x])))))
            (expect (not-any? #(str/includes? % "┌─ Live view") lines))))))))

(defn paint-disclosure-review!
  "Paint a compact receipt or the full nested nodes in the transient band."
  [^TerminalScreen screen pane inline?]
  (.doResizeIfNecessary screen)
  (.clear screen)
  (let [cols
        (.getColumns (.getTerminalSize screen))

        rows
        (.getRows (.getTerminalSize screen))

        g
        (.newTextGraphics screen)]

    (doto g
      (.setBackgroundColor theme/terminal-bg)
      (.setForegroundColor theme/text-fg)
      (.fill \space))
    (.beginFrame interactions/hit-map)
    (if inline?
      (doseq [[row entry] (map-indexed vector (live-view/inline-entries pane (- cols 4)))]
        (live-view/paint-inline-entry! g 2 (inc (long row)) (- cols 4) 0 (:meta entry)))
      (live-view/paint! g cols rows [pane] 1 3))
    (.commitFrame interactions/hit-map)
    (.refresh screen)))

;; #219: only transient views expose nested nodes; both backends share their geometry.
(defdescribe
  live-disclosure-html-native-parity-test
  (it
    "live disclosure html native parity"
    (try
      (doseq [theme-id
              (map keyword (shared-theme/available-theme-ids))

              cols
              [40 80 120]

              recorded?
              [false true]

              inline?
              [false true]]

        (theme/apply-theme! theme-id)
        (with-open [html
                    (activity-review-terminal cols 32)

                    terminal
                    (DefaultVirtualTerminal. (TerminalSize. cols 32))

                    hs
                    (doto (TerminalScreen. html) (.startScreen))

                    ts
                    (doto (TerminalScreen. terminal) (.startScreen))]

          (let [pane (live-fixture/disclosure-review-pane recorded?)]
            (paint-disclosure-review! hs pane inline?)
            (paint-disclosure-review! ts pane inline?)
            (expect (= (cell-grid html cols 32) (cell-grid terminal cols 32)))
            (let [lines (mapv #(apply str
                                 (map (fn [^com.googlecode.lanterna.TextCharacter cell]
                                        (.getCharacterString cell))
                                      %))
                              (cell-grid terminal cols 32))
                  col-of (fn [text]
                           (some #(str/index-of % text) lines))]

              (if inline?
                (do (expect (nil? (col-of "Pool state")))
                    (expect (nil? (col-of "Observed workers")))
                    (expect (nil? (col-of "Other checks")))
                    (expect (every? #(= :live-reopen (:kind %)) (.current interactions/hit-map))))
                (do (expect (= (+ 2 (long (col-of "▾ Pool state"))) (col-of "▾ Observed")))
                    (expect (= (+ 2 (long (col-of "▾ Observed"))) (col-of "monitor revision=42")))
                    ;; #250: both backends keep the Search button on the log header.
                    (expect (some #(and (str/includes? % "▾ Observed") (str/includes? % " Search "))
                                  lines))
                    (expect (= (col-of "▾ Pool state") (col-of "Other checks")))))))))
      (finally (theme/apply-theme! (keyword shared-theme/default-theme-id))))))

(defdescribe
  live-link-grid-html-native-parity-test
  (it "live link grid html native parity"
      ;; #221: one framed link group has identical cells and hit targets in both backends.
      (try
        (doseq [theme-id
                (map keyword (shared-theme/available-theme-ids))

                cols
                [40 80 120]

                recorded?
                [false true]

                inline?
                [false true]]

          (theme/apply-theme! theme-id)
          (with-open [html
                      (activity-review-terminal cols 32)

                      terminal
                      (DefaultVirtualTerminal. (TerminalSize. cols 32))

                      hs
                      (doto (TerminalScreen. html) (.startScreen))

                      ts
                      (doto (TerminalScreen. terminal) (.startScreen))]

            (let [pane (live-fixture/link-grid-review-pane recorded?)]
              (paint-disclosure-review! hs pane inline?)
              (let [html-hits (.current interactions/hit-map)]
                (paint-disclosure-review! ts pane inline?)
                (expect (= html-hits (.current interactions/hit-map))))
              (expect (= (cell-grid html cols 32) (cell-grid terminal cols 32)))
              (let [lines (mapv #(apply str
                                   (map (fn [^com.googlecode.lanterna.TextCharacter cell]
                                          (.getCharacterString cell))
                                        %))
                                (cell-grid terminal cols 32))
                    text (str/join "\n" lines)]

                (if inline?
                  (do (expect (not (str/includes? text "SUCCESS")))
                      (expect (every? #(= :live-reopen (:kind %)) (.current interactions/hit-map))))
                  (do (expect (every? #(str/includes? text (str "Build " % " · SUCCESS"))
                                      (range 1 7)))
                      (expect (some #(str/includes? % "┌") lines))
                      (expect (some #(str/includes? % "└") lines))
                      (when (>= (long cols) 80)
                        (expect (some #(and (str/includes? % "Build 1") (str/includes? % "Build 2"))
                                      lines)))))))))
        (finally (theme/apply-theme! (keyword shared-theme/default-theme-id))))))

(defdescribe
  compact-live-dividers-stay-in-the-transient
  (it
    "compact live dividers stay in the transient"
    (try (doseq [theme-id
                 (map keyword (shared-theme/available-theme-ids))

                 cols
                 [40 80 120]

                 recorded?
                 [false true]]

           (theme/apply-theme! theme-id)
           (with-open [html
                       (activity-review-terminal cols 32)

                       terminal
                       (DefaultVirtualTerminal. (TerminalSize. cols 32))

                       hs
                       (doto (TerminalScreen. html) (.startScreen))

                       ts
                       (doto (TerminalScreen. terminal) (.startScreen))]

             (let [pane (live-fixture/divider-review-pane recorded?)]
               (paint-disclosure-review! hs pane true)
               (paint-disclosure-review! ts pane true)
               (expect (= (cell-grid html cols 32) (cell-grid terminal cols 32)))
               (expect (= 1 (count (live-view/inline-entries pane cols))))
               (expect (= [:live-reopen] (mapv :kind (.current interactions/hit-map))))
               (expect (every?
                         #(not= "─" (.getCharacterString ^com.googlecode.lanterna.TextCharacter %))
                         (mapcat identity (cell-grid terminal cols 32)))))))
         (finally (theme/apply-theme! (keyword shared-theme/default-theme-id))))))

(defdescribe
  live-divider-html-native-parity-test
  (it
    "live divider html native parity"
    (try
      (doseq [theme-id
              (map keyword (shared-theme/available-theme-ids))

              cols
              [40 80 120]

              recorded?
              [false true]]

        (theme/apply-theme! theme-id)
        (with-open [html
                    (activity-review-terminal cols 32)

                    terminal
                    (DefaultVirtualTerminal. (TerminalSize. cols 32))

                    hs
                    (doto (TerminalScreen. html) (.startScreen))

                    ts
                    (doto (TerminalScreen. terminal) (.startScreen))]

          (let [pane (live-fixture/divider-review-pane recorded?)]
            (paint-disclosure-review! hs pane false)
            (let [html-hits (.current interactions/hit-map)]
              (paint-disclosure-review! ts pane false)
              (expect (= html-hits (.current interactions/hit-map)))
              (expect (not-any? #(#{"results-break" "review-break"} (:node-id %)) html-hits)))
            (let [grid (cell-grid terminal cols 32)
                  rules (keep (fn [row]
                                (let [glyph (fn [^com.googlecode.lanterna.TextCharacter cell]
                                              (.getCharacterString cell))
                                      text (apply str (map glyph row))]

                                  ;; Section rules have right padding; outer dialog rails do not.
                                  (when (re-matches #"\s*(?:│\s*)?─+\s+(?:│\s*)?" text)
                                    (filter #(= "─" (glyph %)) row))))
                              grid)]

              (expect (= (cell-grid html cols 32) grid))
              (expect (= 2 (count rules)) "both section rules survive the available height")
              (doseq [^com.googlecode.lanterna.TextCharacter cell (mapcat identity rules)]
                (expect (>= (#'theme-test/contrast-ratio
                             (.getForegroundColor cell)
                             (.getBackgroundColor cell))
                            3.0)
                        (str theme-id " divider contrast")))))))
      (finally (theme/apply-theme! (keyword shared-theme/default-theme-id))))))
