(ns com.blockether.vis.ext.foundation-voice.tts-test
  (:require [clojure.java.io :as io]
            [clojure.string :as str]
            [com.blockether.vis.ext.foundation-voice.assets :as assets]
            [com.blockether.vis.ext.foundation-voice.sherpa :as sherpa]
            [com.blockether.vis.ext.foundation-voice.tts :as tts]
            [com.blockether.vis.ext.foundation-voice.voices :as voices]
            [lazytest.core :refer [defdescribe it expect]]))

(defn- ex-data-of [f] (try (f) nil (catch clojure.lang.ExceptionInfo e (ex-data e))))

(defdescribe
  catalogue-test
  (it "publishes the manifest's Piper voices, the default first"
      (expect (= ["kristin" "cori" "john" "ljspeech" "ryan"]
                 (mapv #(name (:id %)) (tts/piper-voices))))
      (expect (every? :label (tts/piper-voices)))
      (expect (every? :language (tts/piper-voices)))
      (expect (= "kristin" (name (:id (:voice (first (tts/piper-assets))))))))
  (it "ships three reference clips of its own, and resolves each to a file"
      ;; A pocket voice IS a reference clip, and Kyutai's own clips are not ours to
      ;; hand on. These three were generated by `bin/make-voice-clips` from Piper
      ;; voices in the PUBLIC DOMAIN, which makes them Vis' to publish.
      (with-redefs [voices/imported (constantly [])]
        (expect (= ["kristin" "cori" "john"] (mapv :id (:voices (tts/pocket-asset)))))
        (expect (every? :clip-text (:voices (tts/pocket-asset))))
        (expect (= ["kristin" "cori" "john"] (mapv :id (tts/pocket-voices))))
        ;; the catalogue never says which file backs a voice
        (expect (not-any? :clip (tts/pocket-voices)))
        (expect (every? #(str/ends-with? (:clip %) ".wav") (tts/pocket-voice-catalogue)))))
  (it "lets an imported clip stand in for one that shipped"
      ;; Somebody who names their own recording after a shipped voice meant their
      ;; own recording - and a catalogue with the same id twice is a picker bug.
      (with-redefs [tts/pocket-asset
                    (constantly {:id "pocket-tts-int8"
                                 :install-dir "sherpa-onnx-pocket-tts-int8"
                                 :voices
                                 [{:id "kristin" :label "Kristin" :clip "voices/kristin.wav"}]})

                    assets/install-dir
                    (constantly "/models/pocket")

                    voices/imported
                    (constantly [{:id "kristin"
                                  :label "Mine"
                                  :clip "/home/somebody/.vis/voices/kristin.wav"
                                  :is-imported true}])]

        (expect (= ["kristin"] (mapv :id (tts/pocket-voices))))
        (expect (= "Mine" (:label (first (tts/pocket-voices)))))
        (expect (true? (:is-imported (first (tts/pocket-voices)))))
        (expect (= "/home/somebody/.vis/voices/kristin.wav"
                   (:clip (first (tts/pocket-voice-catalogue)))))))
  (it "resolves a shipped clip against the directory the bundle installed into"
      (with-redefs [tts/pocket-asset
                    (constantly {:id "pocket-tts-int8"
                                 :voices [{:id "kristin" :clip "voices/kristin.wav"}]})

                    assets/install-dir
                    (constantly "/models/pocket")

                    voices/imported
                    (constantly [])]

        (expect (= (str (io/file "/models/pocket" "voices/kristin.wav"))
                   (:clip (first (tts/pocket-voice-catalogue)))))))
  (it "refuses to speak with pocket-tts while it has no clip to clone"
      ;; An empty catalogue is not an unknown voice: the failure has to name the
      ;; missing clip, or the user goes looking for a voice id that never existed.
      (with-redefs [sherpa/ensure-native!
                    (constantly nil)

                    assets/installed?
                    (constantly true)

                    voices/imported
                    (constantly [])

                    tts/pocket-asset
                    (constantly (assoc (tts/pocket-asset) :voices []))]

        (let [data (ex-data-of #(tts/synthesize! :pocket-tts {:text "hello"}))]
          (expect (= :voice-tts/no-reference-clips (:type data)))
          (expect (= "pocket-tts-int8" (:asset-id data)))
          (expect (seq (:notice data))))))
  (it "answers an unknown voice with the ones that exist"
      (let [data (ex-data-of #(#'tts/piper-asset-for "nope"))]
        (expect (= :voice-tts/unknown-voice (:type data)))
        (expect (= :piper (:family data)))
        (expect (= ["kristin" "cori" "john" "ljspeech" "ryan"] (:known data)))))
  (it "asks only for the voice, because the phoneme tables are the system's"
      (expect (= ["piper-en_US-kristin-medium"] (mapv :id (#'tts/required-assets :piper nil))))
      (expect (= ["piper-en_GB-cori-high"] (mapv :id (#'tts/required-assets :piper "cori"))))
      (expect (= ["pocket-tts-int8"] (mapv :id (#'tts/required-assets :pocket-tts nil)))))
  (it "marks the voice a user has to install deliberately"
      ;; Ryan is in the catalogue and ONLY in the catalogue: CC BY-NC-SA, so a
      ;; picker can show him with his terms while Vis never fetches him.
      (let [voice
            (last (tts/piper-voices))

            entry
            (last (tts/piper-assets))]

        (expect (= "ryan" (name (:id voice))))
        (expect (true? (:is-opt-in voice)))
        (expect (true? (:is-opt-in entry)))
        (expect (= ["piper-en_US-ryan-high"] (mapv :id (#'tts/required-assets :piper "ryan")))))))

(defdescribe
  readiness-test
  (it "is as ready as its worst part, and its progress never jumps backwards"
      ;; Two parts of one install: the first finishing must not reset it to 0.
      (expect (= {:state :ready} (#'tts/combined-state [{:state :ready} {:state :ready}])))
      (expect (= :absent (:state (#'tts/combined-state [{:state :ready} {:state :absent}]))))
      (let [state (#'tts/combined-state
                   [{:state :ready} {:state :downloading :phase :downloading :progress 40}])]
        (expect (= :downloading (:phase state)))
        (expect (= :downloading (:state state)))
        (expect (= 70 (:progress state))))
      (expect (= :failed
                 (:state (#'tts/combined-state
                          [{:state :failed :error "refused"}
                           {:state :downloading :progress 10}])))))
  (it "refuses a licence-gated VOICE by name instead of reporting absent forever"
      ;; `:absent` with nothing downloading is the one answer a user cannot act
      ;; on, so the refusal carries the command that installs it.
      ;; The phoneme tables are a PRECONDITION of this refusal, not its subject:
      ;; a machine without espeak-ng is refused for THAT first, which is how this
      ;; passed on a developer machine and failed on CI.
      (with-redefs [tts/espeak-data-dir
                    (constantly "/espeak-ng-data")

                    assets/installed?
                    (constantly false)]

        (let [state (tts/start-download! :piper "ryan")]
          (expect (= :failed (:state state)))
          (expect (re-find #"piper-en_US-ryan-high" (:error state)))
          ;; the family alone would install the DEFAULT voice, so the refusal names the
          ;; voice that was actually asked for
          (expect (re-find #"--piper --voice ryan" (:error state))))))
  (it "starts the download of every family Vis fetches by itself"
      (let [started (atom [])]
        ;; espeak-ng belongs to the SYSTEM, so its absence must not decide whether the
        ;; download of a voice starts, and `installed?` answers from what `install!`
        ;; already recorded: the background future settling FIRST would otherwise
        ;; report :absent, which is the race a loaded runner loses.
        (with-redefs [tts/espeak-data-dir (constantly "/espeak-ng-data")
                      assets/installed? (fn [entry]
                                          (boolean (some #{(:id entry)} @started)))
                      assets/install! (fn [entry & _]
                                        (swap! started conj (:id entry))
                                        (:install-dir entry))]

          (let [state (tts/start-download! :piper)]
            (expect (contains? #{:downloading :ready} (:state state))))
          ;; pocket-tts is Vis' own export, so it starts here too instead of refusing
          (let [state (tts/start-download! :pocket-tts)]
            (expect (contains? #{:downloading :ready} (:state state))))
          ;; Settle those installs INSIDE the redefs: a future outliving them would call
          ;; the REAL installer and reach the network.
          (loop [n 0]
            (when (and (< (count @started) 2) (< n 300)) (Thread/sleep 10) (recur (inc n))))
          (expect (= #{"piper-en_US-kristin-medium" "pocket-tts-int8"} (set @started)))))))

(defdescribe install-model-test
             (it "installs everything the named family needs, in one blocking call"
                 ;; The CLI download path is the blocking one: it installs what the family
                 ;; needs and reports the directory it wrote for each asset.
                 (let [installed (atom [])]
                   (with-redefs [sherpa/ensure-native! (constantly nil)
                                 assets/installed? (constantly false)
                                 assets/install! (fn [entry & _]
                                                   (swap! installed conj (:id entry))
                                                   (:install-dir entry))]

                     (expect (= ["sherpa-onnx-pocket-tts-int8"] (tts/install-model! :pocket-tts)))
                     (expect (= ["pocket-tts-int8"] @installed)))))
             (it "installs nothing when everything the voice needs is already there"
                 (with-redefs [sherpa/ensure-native!
                               (constantly nil)

                               assets/installed?
                               (constantly true)

                               assets/install!
                               (fn [& _]
                                 (throw (ex-info "must not download" {})))]

                   (expect (= [] (tts/install-model! :piper))))))

(defdescribe synthesize-test
             (it "refuses blank text before it downloads anything"
                 (with-redefs [assets/ensure!
                               (fn [& _]
                                 (throw (ex-info "must not download" {})))

                               assets/install!
                               (fn [& _]
                                 (throw (ex-info "must not download" {})))]

                   (let [data (ex-data-of #(tts/synthesize! :piper {:text "   "}))]
                     (expect (= :voice-tts/blank-text (:type data)))
                     (expect (= :piper (:family data)))))))

(defdescribe espeak-test
             (it "finds the tables by their contents, not by a directory's name"
                 (let [dir (java.io.File/createTempFile "espeak-ng-data" "")]
                   (try (.delete dir)
                        (.mkdirs dir)
                        (expect (false? (tts/espeak-data-dir? (str dir))))
                        (doseq [f tts/espeak-data-files]
                          (spit (java.io.File. dir ^String f) "x"))
                        (expect (true? (tts/espeak-data-dir? (str dir))))
                        (expect (false? (tts/espeak-data-dir? nil)))
                        (with-redefs [assets/env-value (fn [name]
                                                         (when (= tts/espeak-data-env name)
                                                           (str dir)))]
                          (expect (= (str dir) (tts/espeak-data-dir))))
                        (finally (doseq [f (reverse (file-seq dir))]
                                   (.delete ^java.io.File f))))))
             (it "refuses a Piper voice on a machine without them, and names the command"
                 ;; espeak-ng is GPL-3, everywhere, and read at run time - so Vis never
                 ;; ships it. Missing tables must read as "install this", never as a
                 ;; voice that downloads 63 MB and then cannot speak.
                 (with-redefs [tts/espeak-data-dir (constantly nil)]
                   (let [state (tts/model-state :piper)]
                     (expect (= :failed (:state state)))
                     (expect (str/includes? (:error state) "espeak-ng")))
                   (expect (= :failed (:state (tts/start-download! :piper))))
                   (with-redefs [assets/ensure! (fn [& _]
                                                  (throw (ex-info "must not download" {})))
                                 sherpa/ensure-native! (constantly nil)]

                     (let [data (ex-data-of #(tts/synthesize! :piper {:text "hello"}))]
                       (expect (= :voice-tts/espeak-ng-missing (:type data)))
                       (expect (seq (:remediation data)))
                       (expect (seq (:searched data)))))))
             (it "still reports a pocket voice's readiness without any tables"
                 ;; pocket-tts does not phonemize, so espeak has nothing to do with it.
                 (with-redefs [tts/espeak-data-dir (constantly nil)]
                   (expect (not= :failed (:state (tts/model-state :pocket-tts)))))))

;; Regression, user report: the SHIPPED BINARY died on the first pocket-tts word
;; while the same code spoke from a JVM. sherpa reads `GenerationConfig.extra`
;; from C++ through the map's CONCRETE class - `entrySet`, `iterator`, `hasNext`,
;; `next`, `getKey`, `getValue` - and a Clojure map is one class with eight keys
;; and another with nine, so no metadata entry can name the walk.
(defdescribe
  pocket-generation-config-test
  (it "hands sherpa a map of ONE class, and the clip's own words with it"
      ;; A cold JVM has to provision the library FIRST: this class's own static
      ;; initializer runs sherpa's loader, and after that first touch a missing
      ;; library is permanent for the process.
      (sherpa/ensure-native!)
      (let [clip (java.io.File/createTempFile "vis-pocket-clip-" ".wav")]
        (try (#'voices/write-wav! clip (short-array 24000) 24000)
             (let [gen
                   (#'tts/pocket-generation-config (.getAbsolutePath clip) "what the clip says")]
               (expect (instance? java.util.LinkedHashMap (.getExtra gen))
                       (str "sherpa walks this map through JNI, so its class must be one the"
                            " metadata can name; got "
                            (class (.getExtra gen))))
               (expect (= {"temperature" "0.7" "chunk_size" "15"} (into {} (.getExtra gen))))
               (expect (= "what the clip says" (.getReferenceText gen))))
             (finally (.delete clip))))))
