(ns com.blockether.vis.internal.shim-capabilities
  "What each sandbox shim LENDS, harvested from the Python it installs.

   A shim's prose lives in ONE place: the `__doc__` of the module (or the global
   callable) its own Python builds. Nothing here is hand-written, and no Clojure
   key restates it — `extension/sandbox-shims` declares WIRING (name, imports,
   globals, bindings, source), this namespace answers WHAT THE SANDBOX GETS.

   Harvesting is import-time work: reading `pandas.__doc__` means materializing
   pandas inside a GraalPy context, and lazy shims exist precisely so a session
   that never touches numpy never pays numpy's heap. So the harvest runs at TEST
   time (`shim-capabilities-test/regenerate!`) into `resources/vis-shims/capabilities.edn`,
   and production only READS that resource. A shim whose surface changed without a
   regenerated resource fails that test — the pin is the contract.

   `page` is what `doc(\"pandas\")` answers and what `apropos` ranks, so a member's
   NAME and its one-line docstring are both in it: that is how `apropos(\"read_csv\")`
   reaches the module that lends it. One member's own page is live, not stored —
   `doc(\"pandas.read_csv\")` walks the real object (see `env-python`)."
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.string :as str]))

(def ^:private resource-path
  "Generated by `shim-capabilities-test/regenerate!`; never edited by hand."
  "vis-shims/capabilities.edn")

(def ^:private loaded
  (delay (try (some-> (io/resource resource-path)
                      slurp
                      edn/read-string)
              (catch Throwable _ nil))))

(defn capabilities
  "Every harvested entry, `{import-or-global-name {:kind :sig :doc :names}}`.
   `:names` are the module's own public members, each `{:name :kind :sig :doc}`."
  []
  (or @loaded {}))

(defn entry
  "One harvested entry by the exact name a sandbox types (`\"pandas\"`, `\"attach\"`)."
  [nm]
  (get (capabilities) nm))

(def ^:private kind-labels
  "Print order and label for a member kind."
  [["class" "Classes"] ["function" "Functions"] ["module" "Modules"] ["data" "Data"]])

(defn- member-line
  "`sig — first docstring line`, bounded, for one harvested member."
  [{:keys [sig doc]}]
  (let [d (str/trim (str doc))]
    (if (str/blank? d) sig (str sig " — " (if (> (count d) 90) (str (subs d 0 88) "…") d)))))

(defn page
  "The whole page `doc(name)` answers for a shim import or global: the module's
   own docstring, then every public member it lends, grouped by kind. Returns nil
   when the name was never harvested."
  [nm]
  (when-let [{:keys [doc names]} (entry nm)]
    (let [by-kind (group-by :kind names)
          section (fn [[k label]]
                    (when-let [ms (seq (get by-kind k))]
                      (str label ":\n" (str/join "\n" (map #(str "  " (member-line %)) ms)))))
          body (keep section kind-labels)]

      (str/trim (str/join
                  "\n\n"
                  (cond-> [(str/trim (str doc))]
                    (seq body)
                    (into body)

                    (seq names)
                    (conj (str "Read one member: doc(\"" nm "." (:name (first names)) "\")"))))))))

(defn gist
  "The first line of a shim name's own documentation — its one-line answer."
  [nm]
  (some-> (entry nm)
          :doc
          str/split-lines
          first
          str/trim))

(defn call-line
  "`name(params)` for a shim GLOBAL a sandbox calls directly — the structural line
   its page opens with, never repeated in the prose (see `internal.extension`).
   nil for a module, which nobody calls."
  [nm]
  (when-let [{:keys [kind sig]} (entry nm)]
    (when (and (contains? #{"function" "class"} kind) (not (str/blank? (str sig)))) sig)))
