import { pairingDisplayHost, parseGatewayPairing } from "./GatewayPairing";

describe("gateway QR pairing", () => {
  it("parses the canonical vis:// gateway payload", () => {
    expect(
      parseGatewayPairing(
        "vis://gateway?url=http%3A%2F%2F100.80.1.2%3A7890&token=secret",
      ),
    ).toEqual({ gatewayUrl: "http://100.80.1.2:7890", token: "secret" });
  });

  it("parses JSON payloads generated by gateway tooling", () => {
    expect(
      parseGatewayPairing(
        JSON.stringify({
          type: "vis-gateway-pairing",
          url: "http://192.168.1.10:7890/",
          token: "tok",
        }),
      ),
    ).toEqual({ gatewayUrl: "http://192.168.1.10:7890", token: "tok" });
  });

  it("accepts a plain http URL and strips token query params", () => {
    expect(parseGatewayPairing("http://host:7890?token=tok")).toEqual({
      gatewayUrl: "http://host:7890",
      token: "tok",
    });
  });

  it("accepts a host:port shorthand", () => {
    expect(parseGatewayPairing("100.80.1.2:7890")).toEqual({
      gatewayUrl: "http://100.80.1.2:7890",
    });
  });

  it("throws a useful error for empty scans", () => {
    expect(() => parseGatewayPairing("   ")).toThrow("empty pairing QR");
  });

  it("formats a display host for the settings note", () => {
    expect(pairingDisplayHost({ gatewayUrl: "http://100.80.1.2:7890" })).toBe(
      "100.80.1.2:7890",
    );
  });
});
