// GENERATED by `clojure -X:companion-themes` from
// src/com/blockether/vis/internal/channel/theme.clj — do not edit by hand.

/** Every token a group may carry, in the order a picker offers them. */
export const GROUP_COLORS = [
  'slate',
  'blue',
  'green',
  'amber',
  'red',
  'violet',
  'cyan',
  'pink',
] as const;

export type SessionGroupColor = (typeof GROUP_COLORS)[number];

/** What a group with nothing said about its colour wears — the gateway's default too. */
export const DEFAULT_GROUP_COLOR: SessionGroupColor = 'slate';

/** The class that fills each token's swatch; its hue is `--color-group-<token>`. */
export const GROUP_SWATCHES: Readonly<Record<SessionGroupColor, string>> = {
  slate: 'bg-group-slate',
  blue: 'bg-group-blue',
  green: 'bg-group-green',
  amber: 'bg-group-amber',
  red: 'bg-group-red',
  violet: 'bg-group-violet',
  cyan: 'bg-group-cyan',
  pink: 'bg-group-pink',
};
