// GENERATED by `clojure -X:companion-themes` from
// src/com/blockether/vis/internal/theme.clj — do not edit by hand.

export interface ThemeChoice {
  readonly id: string;
  readonly label: string;
  readonly mode: 'light' | 'dark';
  /** This palette's `--bg`, for the browser chrome's `theme-color` meta. */
  readonly chrome: string;
}

/** Painted before any stored preference is read, and the fallback for an unknown id. */
export const DEFAULT_THEME: ThemeChoice = { id: 'blockether-light', label: 'Blockether Light', mode: 'light', chrome: '#faf3eb' };

export const THEMES: readonly ThemeChoice[] = [
  DEFAULT_THEME,
  { id: 'blockether-dark', label: 'Blockether Dark', mode: 'dark', chrome: '#0f1117' },
  { id: 'solarized-dark', label: 'Solarized Dark', mode: 'dark', chrome: '#002b36' },
  { id: 'solarized-light', label: 'Solarized Light', mode: 'light', chrome: '#fdf6e3' },
  { id: 'vis-dark', label: 'Vis Dark', mode: 'dark', chrome: '#0c0e12' },
  { id: 'vis-light', label: 'Vis Light', mode: 'light', chrome: '#ffffff' },
];
