(ns com.blockether.vis.rlm.corpus.pageindex-test
  "Tests for the PageIndex PDF processing module.
   
   Uses example.pdf from resources-test as the test fixture.
   The PDF has:
   - 1 page
   - Author: Vb1
   - Created with Acrobat PDFMaker 11 for Word
   - Created: 2014-10-22T12:29:10Z"
  (:require
   [babashka.fs :as fs]
   [clojure.java.io :as io]
   [clojure.spec.alpha :as s]
   [lazytest.core :refer [defdescribe describe expect it throws?]]
   [com.blockether.svar.internal.llm :as llm]
   [com.blockether.vis.rlm.corpus.pageindex.pdf :as pdf]
   [com.blockether.vis.rlm :as pageindex]
   [com.blockether.vis.rlm.persistence.schema :as pageindex-spec]
   [com.blockether.vis.rlm.corpus.pageindex.vision :as vision])
  (:import
   [java.awt.image BufferedImage]))

;; =============================================================================
;; Test Constants
;; =============================================================================

(def ^:private TEST_PDF_PATH
  "Path to the test PDF file."
  "resources-test/example.pdf")

(def ^:private TEST_FIXTURE_PATH
  "Path to the expected index fixture directory."
  "resources-test/example-index.pageindex")

;; =============================================================================
;; Fixture: Expected Index for example.pdf
;; =============================================================================

(def ^:private EXAMPLE_PDF_FIXTURE
  "Expected structure from indexing example.pdf.
   
   This fixture represents what a pageindex should produce:
   - :name - 'example' (filename without extension)
   - :extension - 'pdf'
   - :pages - vector with 1 page
   - :toc - vector of TOC entries (may be empty if no TOC in doc)
   - :author - 'Vb1' (from PDF metadata)
   - :created-at - 2014-10-22T12:29:10Z
   - :updated-at - 2014-10-22T12:29:11Z
   
   The :pages structure contains:
   - :index - 0-based page number
   - :nodes - vector of content nodes in reading order
   
   Each node has:
   - :type - :section, :heading, :paragraph, :image, :table, etc.
   - :id - unique string ID within the page
   - :parent-id - parent node ID (nil for root)
   - :content - text content
   - :description - AI-generated description (for sections)
   - :level - h1-h6 for headings, paragraph/citation for paragraphs"
  {:name "example"
   :extension "pdf"
   :author "Vb1"
   :title nil ;; May be inferred by LLM
   :abstract nil ;; May be generated by LLM
   :pages [{:index 0
                     :nodes []}] ;; Nodes filled by LLM extraction
   :toc []}) ;; TOC entries (if present in document)

;; =============================================================================
;; PDF Module Tests (No LLM Required)
;; =============================================================================

(defdescribe pdf-module-test
  (describe "page-count"
    (it "returns correct page count for example.pdf"
      (expect (= 1 (pdf/page-count TEST_PDF_PATH))))

    (it "throws for non-existent file"
      (expect (throws? clojure.lang.ExceptionInfo
                #(pdf/page-count "non-existent.pdf")))))

  (describe "pdf-metadata"
    (it "extracts author from example.pdf"
      (let [meta (pdf/pdf-metadata TEST_PDF_PATH)]
        (expect (= "Vb1" (:author meta)))))

    (it "extracts creator application"
      (let [meta (pdf/pdf-metadata TEST_PDF_PATH)]
        (expect (= "Acrobat PDFMaker 11 für Word" (:creator meta)))))

    (it "extracts producer"
      (let [meta (pdf/pdf-metadata TEST_PDF_PATH)]
        (expect (= "Adobe PDF Library 11.0" (:producer meta)))))

    (it "extracts creation date"
      (let [meta (pdf/pdf-metadata TEST_PDF_PATH)]
        (expect (some? (:created-at meta)))
        (expect (inst? (:created-at meta)))))

    (it "extracts modification date"
      (let [meta (pdf/pdf-metadata TEST_PDF_PATH)]
        (expect (some? (:updated-at meta)))
        (expect (inst? (:updated-at meta)))))

    (it "throws for non-existent file"
      (expect (throws? clojure.lang.ExceptionInfo
                #(pdf/pdf-metadata "non-existent.pdf")))))

  (describe "pdf->images"
    (it "returns vector of BufferedImage"
      (let [images (pdf/pdf->images TEST_PDF_PATH)]
        (expect (vector? images))
        (expect (= 1 (count images)))
        (expect (instance? BufferedImage (first images)))))

    (it "renders at default DPI (150)"
      (let [images (pdf/pdf->images TEST_PDF_PATH)
            img (first images)]
        ;; At 150 DPI, a typical A4 page (~8.27x11.69 inches) renders to ~1240x1754 pixels
        ;; Allow some tolerance for different PDF page sizes
        (expect (> (.getWidth img) 500))
        (expect (> (.getHeight img) 500))))

    (it "renders at custom DPI"
      (let [images-150 (pdf/pdf->images TEST_PDF_PATH {:dpi 150})
            images-300 (pdf/pdf->images TEST_PDF_PATH {:dpi 300})
            img-150 (first images-150)
            img-300 (first images-300)]
        ;; 300 DPI should be ~2x larger than 150 DPI
        (expect (> (.getWidth img-300) (* 1.5 (.getWidth img-150))))
        (expect (> (.getHeight img-300) (* 1.5 (.getHeight img-150))))))

    (it "throws for non-existent file"
      (expect (throws? clojure.lang.ExceptionInfo
                #(pdf/pdf->images "non-existent.pdf")))))

  (describe "pdf->images with :page-set"
    (it "renders only selected pages"
      (let [images (pdf/pdf->images TEST_PDF_PATH {:page-set #{0}})]
        (expect (vector? images))
        (expect (= 1 (count images)))
        (expect (instance? BufferedImage (first images)))))

    (it "empty page-set renders nothing"
      (let [images (pdf/pdf->images TEST_PDF_PATH {:page-set #{}})]
        (expect (vector? images))
        (expect (= 0 (count images)))))

    (it "nil page-set renders all pages (default)"
      (let [images (pdf/pdf->images TEST_PDF_PATH {:page-set nil})]
        (expect (= 1 (count images)))))

    (it "page-set beyond page count renders nothing for that index"
      (let [images (pdf/pdf->images TEST_PDF_PATH {:page-set #{5}})]
        (expect (= 0 (count images))))))

  (describe "detect-text-rotation with :page-set"
    (it "detects rotation only for selected pages"
      (let [rotations (pdf/detect-text-rotation TEST_PDF_PATH {:page-set #{0}})]
        (expect (vector? rotations))
        (expect (= 1 (count rotations)))))

    (it "empty page-set returns empty vector"
      (let [rotations (pdf/detect-text-rotation TEST_PDF_PATH {:page-set #{}})]
        (expect (vector? rotations))
        (expect (= 0 (count rotations)))))

    (it "nil page-set returns all pages (default)"
      (let [rotations (pdf/detect-text-rotation TEST_PDF_PATH)]
        (expect (= 1 (count rotations)))))))

;; =============================================================================
;; Spec Validation Tests (No LLM Required)
;; =============================================================================

(defdescribe spec-validation-test
  (describe "document structure validation"
    (it "validates minimal valid document"
      (let [doc {:name "test"
                 :extension "pdf"
                 :pages [{:index 0
                                   :nodes []}]
                 :toc []}]
        (expect (pageindex-spec/valid-document? doc))))

    (it "rejects document without name"
      (let [doc {:extension "pdf"
                 :pages []
                 :toc []}]
        (expect (not (pageindex-spec/valid-document? doc)))))

    (it "rejects document without extension"
      (let [doc {:name "test"
                 :pages []
                 :toc []}]
        (expect (not (pageindex-spec/valid-document? doc)))))

    (it "validates document with optional fields"
      (let [doc {:name "test"
                 :title "Test Document"
                 :abstract "This is a test."
                 :extension "pdf"
                 :author "Test Author"
                 :pages [{:index 0
                                   :nodes []}]
                 :toc []
                 :created-at (java.time.Instant/now)
                 :updated-at (java.time.Instant/now)}]
        (expect (pageindex-spec/valid-document? doc)))))

  (describe "page structure validation"
    (it "validates page with nodes"
      (let [page {:index 0
                  :nodes [{:type :paragraph
                                :id "1"
                                :content "Test content"}]}]
        (expect (s/valid? ::pageindex-spec/page page))))

    (it "validates page with section and heading"
      (let [page {:index 0
                  :nodes [{:type :section
                                :id "1"
                                :description "A test section"}
                               {:type :heading
                                :id "2"
                                :parent-id "1"
                                :level "h1"
                                :content "Test Heading"}]}]
        (expect (s/valid? ::pageindex-spec/page page)))))

  (describe "TOC entry validation"
    (it "validates complete TOC entry"
      (let [entry {:type :toc-entry
                   :id "uuid-string"
                   :title "Chapter 1"
                   :target-page 0
                   :target-section-id "section-uuid"
                   :level "l1"}]
        (expect (s/valid? ::pageindex-spec/toc-entry entry))))

    (it "validates TOC entry with optional fields"
      (let [entry {:type :toc-entry
                   :id "uuid-string"
                   :parent-id "parent-uuid"
                   :title "Section 1.1"
                   :description "An introduction to the topic"
                   :target-page 5
                   :target-section-id "section-uuid"
                   :level "l2"}]
        (expect (s/valid? ::pageindex-spec/toc-entry entry))))))

;; =============================================================================
;; Fixture Structure Tests (expected index shape)
;; =============================================================================

(defdescribe fixture-structure-test
  (describe "EXAMPLE_PDF_FIXTURE"
    (it "has required document fields"
      (expect (= "example" (:name EXAMPLE_PDF_FIXTURE)))
      (expect (= "pdf" (:extension EXAMPLE_PDF_FIXTURE)))
      (expect (= "Vb1" (:author EXAMPLE_PDF_FIXTURE))))

    (it "has pages vector"
      (expect (vector? (:pages EXAMPLE_PDF_FIXTURE)))
      (expect (= 1 (count (:pages EXAMPLE_PDF_FIXTURE)))))

    (it "has page with correct index"
      (let [page (first (:pages EXAMPLE_PDF_FIXTURE))]
        (expect (= 0 (:index page)))
        (expect (vector? (:nodes page)))))

    (it "has TOC vector"
      (expect (vector? (:toc EXAMPLE_PDF_FIXTURE))))))

;; =============================================================================
;; Test Router
;; =============================================================================

(defn- make-test-router
  "Creates a stub router for tests that don't need real LLM calls."
  []
  (llm/make-router [{:id :test :api-key "test" :base-url "http://localhost"
                     :models [{:name "gpt-4o"}
                              {:name "gpt-4o-mini"}]}]))

;; =============================================================================
;; Core API Tests (No LLM - file detection only)
;; =============================================================================

(defdescribe core-api-test
  (describe "file type detection"
    (it "detects PDF files exist"
      (expect (.exists (io/file TEST_PDF_PATH))))

    (it "throws for non-existent file"
      ;; Test via the build-index error path - file exists check
      (expect (throws? clojure.lang.ExceptionInfo
                #(pageindex/build-index (make-test-router) "non-existent.pdf"))))))

;; =============================================================================
;; Integration Tests (Requires LLM - marked for conditional execution)
;; =============================================================================

(defn- make-integration-router
  "Creates a router for integration tests from env vars. Returns nil if no API key."
  []
  (when-let [api-key (System/getenv "OPENAI_API_KEY")]
    (llm/make-router [{:id :openai
                       :api-key api-key
                       :base-url (or (System/getenv "OPENAI_BASE_URL")
                                   "https://api.openai.com/v1")
                       :models [{:name "gpt-4o"}
                                {:name "gpt-4o-mini"}]}])))

(defdescribe build-index-integration-test
  (describe "build-index for example.pdf"
    (it "produces valid document structure (when LLM available)"
      (when-let [router (make-integration-router)]
        (let [doc (pageindex/build-index router TEST_PDF_PATH)]
          ;; Check required fields
          (expect (= "example" (:name doc)))
          (expect (= "pdf" (:extension doc)))

          ;; Check pages
          (expect (vector? (:pages doc)))
          (expect (= 1 (count (:pages doc))))

          ;; Check page structure
          (let [page (first (:pages doc))]
            (expect (= 0 (:index page)))
            (expect (vector? (:nodes page))))

          ;; Check TOC
          (expect (vector? (:toc doc)))

          ;; Check metadata from PDF
          (expect (= "Vb1" (:author doc)))
          (expect (inst? (:created-at doc)))

          ;; Validate against spec
          (expect (pageindex-spec/valid-document? doc)))))

    (it "index! saves and load-index reads back (when LLM available)"
      (when-let [router (make-integration-router)]
        (let [output-path "resources-test/example-generated.pageindex"
              result (pageindex/index! TEST_PDF_PATH
                       {:router router
                        :output output-path})
              loaded (pageindex/load-index output-path)]
          (try
            ;; Check result structure
            (expect (some? (:document result)))
            (expect (= output-path (:output-path result)))

            ;; Check loaded matches original
            (expect (= (:name (:document result))
                      (:name loaded)))
            (expect (= (:extension (:document result))
                      (:extension loaded)))

            ;; Validate loaded document
            (expect (pageindex-spec/valid-document? loaded))
            (finally
              ;; Cleanup
              (fs/delete-tree output-path))))))))

;; =============================================================================
;; Fixture Loading Tests
;; =============================================================================

(defdescribe fixture-loading-test
  (describe "load saved index"
    (it "loads fixture index when available"
      (when (fs/exists? TEST_FIXTURE_PATH)
        (let [doc (pageindex/load-index TEST_FIXTURE_PATH)]
          (expect (= "example" (:name doc)))
          (expect (pageindex-spec/valid-document? doc)))))))

;; =============================================================================
;; build-index Output Dir Tests (No LLM)
;; =============================================================================

(defdescribe build-index-output-dir-test
  (describe "build-index :path with output-dir"
    (it "writes PNG files for visual nodes"
      (let [output-dir (fs/create-temp-dir {:prefix "pageindex-output-"})
            fake-pages [{:index 0
                         :nodes [{:type :image
                                       :id "img-1"
                                       :image-data (byte-array [1 2 3])
                                       :description "diagram"}]}]]
        (try
          (with-redefs [com.blockether.vis.rlm/extract-text (fn [_ _] fake-pages)
                        com.blockether.vis.rlm/generate-document-abstract (fn [_ _] nil)
                        vision/infer-document-title (fn [_ _] nil)]
            (let [doc (pageindex/build-index nil TEST_PDF_PATH {:output-dir (str output-dir)})
                  node-id (get-in doc [:pages 0 :nodes 0 :id])
                  img-path (fs/path output-dir (str node-id ".png"))]
              (expect (fs/exists? img-path))))
          (finally
            (fs/delete-tree output-dir))))))

  (describe "build-index :path without output-dir"
    (it "retains image bytes in returned structure"
      (let [fake-pages [{:index 0
                         :nodes [{:type :image
                                       :id "img-1"
                                       :image-data (byte-array [9 9 9])
                                       :description "diagram"}]}]]
        (with-redefs [com.blockether.vis.rlm/extract-text (fn [_ _] fake-pages)
                      com.blockether.vis.rlm/generate-document-abstract (fn [_ _] nil)
                      vision/infer-document-title (fn [_ _] nil)]
          (let [doc (pageindex/build-index nil TEST_PDF_PATH)
                img-bytes (get-in doc [:pages 0 :nodes 0 :image-data])]
            (expect (bytes? img-bytes)))))))

  (describe "build-index :string ignores output-dir"
    (it "does not fail when output-dir is set"
      (with-redefs [vision/extract-text-from-string
                    (fn [_ _] [{:index 0
                                :nodes [{:type :paragraph
                                              :id "p1"
                                              :content "hello"}]}])
                    com.blockether.vis.rlm/generate-document-abstract (fn [_ _] nil)
                    vision/infer-document-title (fn [_ _] nil)]
        (let [doc (pageindex/build-index nil "Hello" {:content-type :txt
                                                      :doc-name "sample"
                                                      :output-dir "missing"})]
          (expect (= "sample" (:name doc))))))))

;; =============================================================================
;; Table ASCII Content Tests (No LLM)
;; =============================================================================

(defdescribe table-ascii-content-test
  (describe "table nodes with :content"
    (it "preserves ASCII table content through build-index pipeline"
      (let [ascii-table "| Name  | Age |\n|-------|-----|\n| Alice | 30  |\n| Bob   | 25  |"
            fake-pages [{:index 0
                         :nodes [{:type :section
                                       :id "1"
                                       :description "Data section"}
                                      {:type :heading
                                       :id "2"
                                       :parent-id "1"
                                       :level "h1"
                                       :content "Results"}
                                      {:type :table
                                       :id "3"
                                       :parent-id "1"
                                       :kind "data"
                                       :bbox [10 20 300 200]
                                       :description "A table showing names and ages"
                                       :content ascii-table}]}]]
        (with-redefs [com.blockether.vis.rlm/extract-text (fn [_ _] fake-pages)
                      com.blockether.vis.rlm/generate-document-abstract (fn [_ _] nil)
                      vision/infer-document-title (fn [_ _] nil)]
          (let [doc (pageindex/build-index nil TEST_PDF_PATH)
                table-node (->> (get-in doc [:pages 0 :nodes])
                             (filter #(= :table (:type %)))
                             first)]
            (expect (some? table-node))
            (expect (= ascii-table (:content table-node)))
            (expect (= "A table showing names and ages" (:description table-node)))))))

    (it "validates table node with content against spec"
      (let [table-node {:type :table
                        :id "t1"
                        :kind "data"
                        :bbox [0 0 100 100]
                        :description "Test table"
                        :content "| A | B |\n|---|---|\n| 1 | 2 |"}]
        (expect (s/valid? ::pageindex-spec/content-node table-node))))

    (it "validates table node without content against spec"
      (let [table-node {:type :table
                        :id "t1"
                        :kind "data"
                        :bbox [0 0 100 100]
                        :description "Test table"}]
        (expect (s/valid? ::pageindex-spec/content-node table-node))))

    (it "table content survives ID translation"
      (let [ascii-table "| X | Y |\n|---|---|\n| 1 | 2 |"
            pages [{:index 0
                    :nodes [{:type :table
                                  :id "1"
                                  :kind "data"
                                  :bbox [0 0 100 100]
                                  :description "Test"
                                  :content ascii-table}]}]
            translated (pageindex/group-continuations
                         (#'com.blockether.vis.rlm/translate-all-ids pages))
            table-node (first (:nodes (first translated)))]
        (expect (= ascii-table (:content table-node)))
                  ;; ID should be translated to UUID
        (expect (not= "1" (:id table-node)))))))

;; =============================================================================
;; Cambridge Guide to Schema Therapy — Fixture Tests
;; =============================================================================
;;
;; Each test loads a pre-generated .pageindex fixture and validates:
;; 1. Spec compliance (::pageindex-spec/document)
;; 2. Structural expectations per PDF type (pages, TOC, node types)
;; 3. Round-trip integrity (load-index reads what index! wrote)

(def ^:private CAMBRIDGE_DIR
  "resources-test")

(defn- cambridge-fixture-path
  "Returns the .pageindex path for a cambridge test PDF."
  [base-name]
  (str CAMBRIDGE_DIR "/" base-name ".pageindex"))

(defn- load-cambridge-fixture
  "Loads a cambridge fixture if it exists. Returns nil if not generated yet."
  [base-name]
  (let [path (cambridge-fixture-path base-name)]
    (when (fs/exists? path)
      (pageindex/load-index path))))

(defn- all-nodes
  "Extracts all page nodes from a document."
  [doc]
  (->> (:pages doc)
    (mapcat :nodes)
    vec))

(defn- nodes-of-type
  "Filters all page nodes by type."
  [doc node-type]
  (->> (all-nodes doc)
    (filter #(= node-type (:type %)))
    vec))

(defdescribe cambridge-toc-test
  (describe "toc.pdf fixture"
    (it "passes spec validation"
      (when-let [doc (load-cambridge-fixture "toc")]
        (expect (pageindex-spec/valid-document? doc))))

    (it "has correct document metadata"
      (when-let [doc (load-cambridge-fixture "toc")]
        (expect (= "toc" (:name doc)))
        (expect (= "pdf" (:extension doc)))))

    (it "has 2 pages"
      (when-let [doc (load-cambridge-fixture "toc")]
        (expect (= 2 (count (:pages doc))))))

    (it "has non-empty TOC entries"
      (when-let [doc (load-cambridge-fixture "toc")]
        (expect (pos? (count (:toc doc))))))

    (it "TOC entries have required fields"
      (when-let [doc (load-cambridge-fixture "toc")]
        (doseq [entry (:toc doc)]
          (expect (some? (:id entry)))
          (expect (some? (:title entry)))
          (expect (some? (:level entry)))
          (expect (nat-int? (:target-page entry))))))))

(defdescribe cambridge-box-multi-page-test
  (describe "box-multi-page.pdf fixture"
    (it "passes spec validation"
      (when-let [doc (load-cambridge-fixture "box-multi-page")]
        (expect (pageindex-spec/valid-document? doc))))

    (it "has correct document metadata"
      (when-let [doc (load-cambridge-fixture "box-multi-page")]
        (expect (= "box-multi-page" (:name doc)))
        (expect (= "pdf" (:extension doc)))))

    (it "has multiple pages"
      (when-let [doc (load-cambridge-fixture "box-multi-page")]
        (expect (> (count (:pages doc)) 1))))

    (it "has section and heading nodes"
      (when-let [doc (load-cambridge-fixture "box-multi-page")]
        (expect (pos? (count (nodes-of-type doc :section))))
        (expect (pos? (count (nodes-of-type doc :heading))))))))

(defdescribe cambridge-box-conversations-test
  (describe "box-conversations.pdf fixture"
    (it "passes spec validation"
      (when-let [doc (load-cambridge-fixture "box-conversations")]
        (expect (pageindex-spec/valid-document? doc))))

    (it "has correct metadata"
      (when-let [doc (load-cambridge-fixture "box-conversations")]
        (expect (= "box-conversations" (:name doc)))))

    (it "has paragraph content"
      (when-let [doc (load-cambridge-fixture "box-conversations")]
        (expect (pos? (count (nodes-of-type doc :paragraph))))))))

(defdescribe cambridge-table-multi-page-test
  (describe "table-multi-page.pdf fixture"
    (it "passes spec validation"
      (when-let [doc (load-cambridge-fixture "table-multi-page")]
        (expect (pageindex-spec/valid-document? doc))))

    (it "has table nodes"
      (when-let [doc (load-cambridge-fixture "table-multi-page")]
        (expect (pos? (count (nodes-of-type doc :table))))))))

(defdescribe cambridge-table-rotated-test
  (describe "table-multi-page-rotated.pdf fixture"
    (it "passes spec validation"
      (when-let [doc (load-cambridge-fixture "table-multi-page-rotated")]
        (expect (pageindex-spec/valid-document? doc))))

    (it "has table nodes"
      (when-let [doc (load-cambridge-fixture "table-multi-page-rotated")]
        (expect (pos? (count (nodes-of-type doc :table))))))))

(defdescribe cambridge-chapter-test
  (describe "chapter.pdf fixture"
    (it "passes spec validation"
      (when-let [doc (load-cambridge-fixture "chapter")]
        (expect (pageindex-spec/valid-document? doc))))

    (it "has multiple pages"
      (when-let [doc (load-cambridge-fixture "chapter")]
        (expect (> (count (:pages doc)) 1))))

    (it "has sections, headings, and paragraphs"
      (when-let [doc (load-cambridge-fixture "chapter")]
        (expect (pos? (count (nodes-of-type doc :section))))
        (expect (pos? (count (nodes-of-type doc :heading))))
        (expect (pos? (count (nodes-of-type doc :paragraph))))))

    (it "has non-empty TOC"
      (when-let [doc (load-cambridge-fixture "chapter")]
        (expect (pos? (count (:toc doc))))))))

(defdescribe cambridge-figure-diagram-1-test
  (describe "figure-diagram-1.pdf fixture"
    (it "passes spec validation"
      (when-let [doc (load-cambridge-fixture "figure-diagram-1")]
        (expect (pageindex-spec/valid-document? doc))))

    (it "has image nodes"
      (when-let [doc (load-cambridge-fixture "figure-diagram-1")]
        (expect (pos? (count (nodes-of-type doc :image))))))))

(defdescribe cambridge-figure-diagram-2-test
  (describe "figure-diagram-2.pdf fixture"
    (it "passes spec validation"
      (when-let [doc (load-cambridge-fixture "figure-diagram-2")]
        (expect (pageindex-spec/valid-document? doc))))

    (it "has image nodes"
      (when-let [doc (load-cambridge-fixture "figure-diagram-2")]
        (expect (pos? (count (nodes-of-type doc :image))))))))

(defdescribe cambridge-illustration-test
  (describe "illustration.pdf fixture"
    (it "passes spec validation"
      (when-let [doc (load-cambridge-fixture "illustration")]
        (expect (pageindex-spec/valid-document? doc))))

    (it "has image nodes"
      (when-let [doc (load-cambridge-fixture "illustration")]
        (expect (pos? (count (nodes-of-type doc :image))))))))

(defdescribe cambridge-figure-advanced-1-test
  (describe "figure-advanced-1.pdf fixture"
    (it "passes spec validation"
      (when-let [doc (load-cambridge-fixture "figure-advanced-1")]
        (expect (pageindex-spec/valid-document? doc))))

    (it "has image nodes with descriptions"
      (when-let [doc (load-cambridge-fixture "figure-advanced-1")]
        (let [imgs (nodes-of-type doc :image)]
          (expect (pos? (count imgs)))
          (expect (every? #(some? (:description %)) imgs)))))))

(defdescribe cambridge-figure-advanced-2-test
  (describe "figure-advanced-2.pdf fixture"
    (it "passes spec validation"
      (when-let [doc (load-cambridge-fixture "figure-advanced-2")]
        (expect (pageindex-spec/valid-document? doc))))

    (it "has image nodes"
      (when-let [doc (load-cambridge-fixture "figure-advanced-2")]
        (expect (pos? (count (nodes-of-type doc :image))))))))

;; =============================================================================
;; Rotation Detection & Correction Tests (No LLM — pure image rotation)
;; =============================================================================

(defdescribe rotate-image-test
  (describe "rotate-image utility"
    (it "0 degrees returns same image"
      (let [img (BufferedImage. 100 200 BufferedImage/TYPE_INT_RGB)
            rotated (#'vision/rotate-image img 0)]
        (expect (identical? img rotated))))

    (it "90 degrees swaps width and height"
      (let [img (BufferedImage. 100 200 BufferedImage/TYPE_INT_RGB)
            rotated (#'vision/rotate-image img 90)]
        (expect (= 200 (.getWidth rotated)))
        (expect (= 100 (.getHeight rotated)))))

    (it "180 degrees preserves dimensions"
      (let [img (BufferedImage. 100 200 BufferedImage/TYPE_INT_RGB)
            rotated (#'vision/rotate-image img 180)]
        (expect (= 100 (.getWidth rotated)))
        (expect (= 200 (.getHeight rotated)))))

    (it "270 degrees swaps width and height"
      (let [img (BufferedImage. 100 200 BufferedImage/TYPE_INT_RGB)
            rotated (#'vision/rotate-image img 270)]
        (expect (= 200 (.getWidth rotated)))
        (expect (= 100 (.getHeight rotated)))))

    (it "preserves pixel data through 90° rotation"
                ;; Paint top-left corner red, verify it moves to top-right after 90° CW
      (let [img (BufferedImage. 4 2 BufferedImage/TYPE_INT_RGB)
            _ (.setRGB img 0 0 0xFF0000) ;; red at (0,0)
            rotated (#'vision/rotate-image img 90)]
                  ;; After 90° CW: (0,0) in src → (1,0) in dst (top-right of 2×4 image)
                  ;; Height of rotated = src width = 4, Width of rotated = src height = 2
        (expect (= 2 (.getWidth rotated)))
        (expect (= 4 (.getHeight rotated)))))))

(defdescribe cambridge-all-fixtures-common-test
  (describe "common invariants across all cambridge fixtures"
    (it "all generated fixtures have non-empty pages with nodes"
      (doseq [base-name ["toc" "box-multi-page" "box-conversations"
                         "table-multi-page" "table-multi-page-rotated"
                         "figure-diagram-1" "figure-diagram-2"
                         "illustration" "figure-advanced-1"
                         "chapter" "figure-advanced-2"]]
        (when-let [doc (load-cambridge-fixture base-name)]
          (expect (pos? (count (:pages doc)))
            (str base-name " should have pages"))
          (expect (pos? (count (all-nodes doc)))
            (str base-name " should have nodes")))))

    (it "all nodes have required :type and :id"
      (doseq [base-name ["toc" "box-multi-page" "box-conversations"
                         "table-multi-page" "table-multi-page-rotated"
                         "figure-diagram-1" "figure-diagram-2"
                         "illustration" "figure-advanced-1"
                         "chapter" "figure-advanced-2"]]
        (when-let [doc (load-cambridge-fixture base-name)]
          (doseq [node (all-nodes doc)]
            (expect (some? (:type node))
              (str base-name " node missing :type"))
            (expect (some? (:id node))
              (str base-name " node missing :id"))))))

    (it "page indices are sequential starting from 0"
      (doseq [base-name ["toc" "box-multi-page" "box-conversations"
                         "table-multi-page" "table-multi-page-rotated"
                         "figure-diagram-1" "figure-diagram-2"
                         "illustration" "figure-advanced-1"
                         "chapter" "figure-advanced-2"]]
        (when-let [doc (load-cambridge-fixture base-name)]
          (let [indices (mapv :index (:pages doc))]
            (expect (= (range (count indices)) indices)
              (str base-name " page indices not sequential"))))))))

;; =============================================================================
;; Page Range Support Tests (TDD Red Phase)
;; =============================================================================

(defn- throws-with-type?
  "Calls f and checks that it throws ExceptionInfo with the given :type in ex-data."
  [expected-type f]
  (try
    (f)
    false
    (catch clojure.lang.ExceptionInfo e
      (= expected-type (:type (ex-data e))))))

(defdescribe normalize-page-spec-test
  (describe "happy paths"
    (it "nil returns nil (all pages)"
      (expect (nil? (pageindex/normalize-page-spec nil 10))))

    (it "single integer converts 1-indexed to 0-indexed"
      (expect (= #{2} (pageindex/normalize-page-spec 3 10))))

    (it "first page"
      (expect (= #{0} (pageindex/normalize-page-spec 1 10))))

    (it "last page"
      (expect (= #{9} (pageindex/normalize-page-spec 10 10))))

    (it "range vector expands to 0-indexed set"
      (expect (= #{0 1 2} (pageindex/normalize-page-spec [1 3] 10))))

    (it "single-element range where start equals end"
      (expect (= #{4} (pageindex/normalize-page-spec [5 5] 10))))

    (it "mixed vector of ranges and singles"
      (expect (= #{0 1 2 4 6 7 8 9}
                (pageindex/normalize-page-spec [[1 3] 5 [7 10]] 10))))

    (it "multiple disjoint ranges"
      (expect (= #{0 1 3 4}
                (pageindex/normalize-page-spec [[1 2] [4 5]] 10))))

    (it "full range covering all pages"
      (expect (= #{0 1 2 3 4 5 6 7 8 9}
                (pageindex/normalize-page-spec [1 10] 10)))))

  (describe "validation errors"
    (it "page number 0 throws invalid-page-spec"
      (expect (throws-with-type?
                :svar.pageindex/invalid-page-spec
                #(pageindex/normalize-page-spec 0 10))))

    (it "negative page number throws invalid-page-spec"
      (expect (throws-with-type?
                :svar.pageindex/invalid-page-spec
                #(pageindex/normalize-page-spec -1 10))))

    (it "page beyond total throws page-out-of-bounds"
      (expect (throws-with-type?
                :svar.pageindex/page-out-of-bounds
                #(pageindex/normalize-page-spec 11 10))))

    (it "reversed range throws invalid-page-range"
      (expect (throws-with-type?
                :svar.pageindex/invalid-page-range
                #(pageindex/normalize-page-spec [5 3] 10))))

    (it "out-of-bounds page in mixed vector throws page-out-of-bounds"
      (expect (throws-with-type?
                :svar.pageindex/page-out-of-bounds
                #(pageindex/normalize-page-spec [[1 3] 15] 10))))

    (it "string input throws invalid-page-spec"
      (expect (throws-with-type?
                :svar.pageindex/invalid-page-spec
                #(pageindex/normalize-page-spec "foo" 10))))

    (it "non-integer in range throws invalid-page-spec"
      (expect (throws-with-type?
                :svar.pageindex/invalid-page-spec
                #(pageindex/normalize-page-spec [1 "foo"] 10))))))

(def ^:private sample-pages
  "Sample page-list for filter-pages tests."
  [{:index 0 :nodes ["a"]}
   {:index 1 :nodes ["b"]}
   {:index 2 :nodes ["c"]}
   {:index 3 :nodes ["d"]}
   {:index 4 :nodes ["e"]}])

(defdescribe filter-pages-test
  (describe "page filtering"
    (it "nil page-set returns all pages"
      (expect (= sample-pages
                (pageindex/filter-pages sample-pages nil))))

    (it "single page set returns matching page"
      (expect (= [(first sample-pages)]
                (pageindex/filter-pages sample-pages #{0}))))

    (it "multiple pages in set returns matching pages in order"
      (expect (= [(nth sample-pages 0)
                  (nth sample-pages 2)
                  (nth sample-pages 4)]
                (pageindex/filter-pages sample-pages #{0 2 4}))))

    (it "empty set returns empty vector"
      (expect (= []
                (pageindex/filter-pages sample-pages #{}))))

    (it "empty page-list returns empty vector"
      (expect (= []
                (pageindex/filter-pages [] #{0 1}))))))

;; =============================================================================
;; build-index :path with :pages option (TDD)
;; =============================================================================

(defdescribe build-index-pages-filter-test
  (describe "build-index :path with :pages option"
    ;; PDF filtering happens at the vision layer (extract-text-from-pdf).
    ;; The mocks below simulate that by pre-filtering the returned page list.
    (it "filters pages from extraction output"
      (let [fake-pages [{:index 1 :nodes [{:type :paragraph :id "p1" :content "Page 1"}]}
                        {:index 2 :nodes [{:type :paragraph :id "p2" :content "Page 2"}]}
                        {:index 3 :nodes [{:type :paragraph :id "p3" :content "Page 3"}]}]]
        (with-redefs [com.blockether.vis.rlm/extract-text
                      (fn [_ _] fake-pages)
                      com.blockether.vis.rlm/generate-document-abstract
                      (fn [_ _] nil)
                      com.blockether.vis.rlm.corpus.pageindex.vision/infer-document-title
                      (fn [_ _] nil)]
          (let [doc (pageindex/build-index nil "resources-test/example.pdf" {:pages [2 4]})]
            (expect (= 3 (count (:pages doc))))
            (expect (= [1 2 3] (mapv :index (:pages doc))))))))

    (it "single page integer works"
      (let [fake-pages [{:index 2 :nodes [{:type :paragraph :id "p2" :content "Page 2"}]}]]
        (with-redefs [com.blockether.vis.rlm/extract-text
                      (fn [_ _] fake-pages)
                      com.blockether.vis.rlm/generate-document-abstract
                      (fn [_ _] nil)
                      com.blockether.vis.rlm.corpus.pageindex.vision/infer-document-title
                      (fn [_ _] nil)]
          (let [doc (pageindex/build-index nil "resources-test/example.pdf" {:pages 3})]
            (expect (= 1 (count (:pages doc))))
            (expect (= [2] (mapv :index (:pages doc))))))))

    (it "nil pages returns all pages (default behavior)"
      (let [fake-pages (mapv (fn [i] {:index i
                                      :nodes [{:type :paragraph
                                                    :id (str "p" i)
                                                    :content (str "Page " i)}]})
                         (range 3))]
        (with-redefs [com.blockether.vis.rlm/extract-text
                      (fn [_ _] fake-pages)
                      com.blockether.vis.rlm/generate-document-abstract
                      (fn [_ _] nil)
                      com.blockether.vis.rlm.corpus.pageindex.vision/infer-document-title
                      (fn [_ _] nil)]
          (let [doc (pageindex/build-index nil "resources-test/example.pdf")]
            (expect (= 3 (count (:pages doc))))))))

    (it "out-of-bounds pages raises at vision layer"
      ;; With the vision-layer-filters-PDFs invariant, build-index no longer
      ;; validates :pages against the file's true length. The vision extractor
      ;; is responsible for raising if requested pages exceed the document.
      (with-redefs [com.blockether.vis.rlm/extract-text
                    (fn [_ opts]
                      (throw (ex-info "page index out of range"
                               {:type :svar.pageindex/pages-out-of-range
                                :pages (:pages opts)})))]
        (expect (throws? clojure.lang.ExceptionInfo
                  #(pageindex/build-index nil "resources-test/example.pdf" {:pages 5})))))))

(defdescribe extract-text-from-pdf-page-set-test
  (describe "extract-text-from-pdf with :page-set"
    (it "only sends selected pages to vision LLM"
      ;; Track which page indices hit the vision extractor
      (let [extracted-pages (atom [])]
        (with-redefs [vision/extract-text-from-image
                      (fn [_image page-index _opts]
                        (swap! extracted-pages conj page-index)
                        {:index page-index
                         :nodes [{:type :paragraph
                                       :id (str "p" page-index)
                                       :content (str "Page " page-index)}]})]
          ;; example.pdf has 1 page (index 0). Request only page 1 (1-indexed = index 0).
          (let [result (vision/extract-text-from-pdf TEST_PDF_PATH
                         {:model "test"
                          :objective "test"
                          :page-set #{0}})]
            (expect (= 1 (count result)))
            (expect (= [0] @extracted-pages))
            (expect (= 0 (:index (first result))))))))

    (it "nil page-set extracts all pages"
      (let [extracted-pages (atom [])]
        (with-redefs [vision/extract-text-from-image
                      (fn [_image page-index _opts]
                        (swap! extracted-pages conj page-index)
                        {:index page-index
                         :nodes [{:type :paragraph
                                       :id (str "p" page-index)
                                       :content (str "Page " page-index)}]})]
          (let [result (vision/extract-text-from-pdf TEST_PDF_PATH
                         {:model "test"
                          :objective "test"})]
            (expect (= 1 (count result)))
            (expect (= [0] @extracted-pages))))))))
